# Generated by Django 5.0.14 on 2025-05-08 02:28

import cadastros.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoWpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('dt_inicio', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Sessão do WhatsApp',
                'verbose_name_plural': 'Sessões do WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='Aplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('device_has_mac', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConteudoM3U8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capa', models.URLField()),
                ('temporada', models.IntegerField(blank=True, null=True)),
                ('episodio', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('upload', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conteúdo M3U8',
                'verbose_name_plural': 'Conteúdos M3U8',
            },
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpp', models.CharField(max_length=20)),
                ('beneficiario', models.CharField(max_length=255)),
                ('instituicao', models.CharField(max_length=255)),
                ('tipo_chave', models.CharField(max_length=255)),
                ('chave', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dados Bancários',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de vencimento inicial')),
                ('data_adesao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de adesão')),
                ('data_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data de cancelamento')),
                ('ultimo_pagamento', models.DateField(blank=True, null=True, verbose_name='Último pagamento realizado')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Cancelado')),
                ('nao_enviar_msgs', models.BooleanField(default=False, verbose_name='Não enviar')),
                ('enviado_oferta_promo', models.BooleanField(default=False, verbose_name='Oferta PROMO')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('indicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.cliente')),
                ('sistema', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.aplicativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.dispositivo')),
            ],
            options={
                'ordering': ['-data_adesao'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEnvios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField(null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horário de Envio',
                'verbose_name_plural': 'Horarios de Envio',
            },
        ),
        migrations.CreateModel(
            name='MensagemEnviadaWpp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem Enviada ao WhatsApp',
                'verbose_name_plural': 'Mensagens Enviadas ao WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=None, max_digits=5, verbose_name='Valor')),
                ('dt_vencimento', models.DateField(default=cadastros.models.default_vencimento, verbose_name='Data do vencimento')),
                ('dt_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('dt_cancelamento', models.DateField(blank=True, null=True, verbose_name='Data do cancelamento')),
                ('dt_notif_wpp1', models.DateField(blank=True, null=True, verbose_name='Data envio notificação PROMO')),
                ('pgto', models.BooleanField(default=False, verbose_name='Pago')),
                ('cancelado', models.BooleanField(default=False)),
                ('notificacao_wpp1', models.BooleanField(default=False, verbose_name='Notificação PROMO')),
                ('recebeu_pix_indicacao', models.BooleanField(default=False, verbose_name='PIX R$50')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensal', max_length=255, verbose_name='Nome do plano')),
                ('telas', models.IntegerField(default=1, verbose_name='Número de telas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.plano'),
        ),
        migrations.CreateModel(
            name='PlanoIndicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_plano', models.CharField(choices=[('desconto', 'Desconto na mensalidade'), ('dinheiro', 'Valor em dinheiro')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor para desconto ou bonificação')),
                ('valor_minimo_mensalidade', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor mínimo a ser mantido na mensalidade')),
                ('ativo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Planos de Indicação',
            },
        ),
        migrations.CreateModel(
            name='SecretTokenAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secret Token API',
                'verbose_name_plural': 'Secrets Tokens API',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('CLUB', 'CLUB'), ('PlayON', 'PlayON'), ('ALPHA', 'ALPHA'), ('SEVEN', 'SEVEN'), ('FIVE', 'FIVE')], max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Servidores',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.servidor'),
        ),
        migrations.CreateModel(
            name='Tipos_pgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('PIX', 'PIX'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Boleto', 'Boleto')], default='PIX', max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Pagamento',
                'verbose_name_plural': 'Tipos de Pagamentos',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='forma_pgto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.tipos_pgto', verbose_name='Forma de pagamento'),
        ),
        migrations.CreateModel(
            name='ContaDoAplicativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('device_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('verificado', models.BooleanField(default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicativos', to='cadastros.aplicativo', verbose_name='Aplicativo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_aplicativo', to='cadastros.cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta do Aplicativo',
                'verbose_name_plural': 'Contas dos Aplicativos',
                'indexes': [models.Index(fields=['cliente', 'app'], name='cadastros_c_cliente_d49878_idx'), models.Index(fields=['device_id'], name='cadastros_c_device__90d23d_idx')],
            },
        ),
    ]
