# Generated by Django 4.2 on 2023-06-03 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(
                default=datetime.date(2023, 6, 3), verbose_name='Data de adesão'
            ),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(
                default=datetime.date(2023, 7, 3), verbose_name='Data do vencimento'
            ),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(
                choices=[
                    ('Mensal', 'Mensal'),
                    ('Trimestral', 'Trimestral'),
                    ('Semestral', 'Semestral'),
                    ('Anual', 'Anual'),
                ],
                default='Mensal',
                max_length=255,
                verbose_name='Nome do plano',
            ),
        ),
    ]
