<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-06-08 03:11
=======
# Generated by Django 4.2 on 2023-06-03 17:18
>>>>>>> 0b41b9008ba417b31db9cf1b88ad446e9eb9c078

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

=======
>>>>>>> 0b41b9008ba417b31db9cf1b88ad446e9eb9c078
    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2023, 6, 8), verbose_name='Data de adesão'),
=======
            field=models.DateField(
                default=datetime.date(2023, 6, 3), verbose_name='Data de adesão'
            ),
>>>>>>> 0b41b9008ba417b31db9cf1b88ad446e9eb9c078
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
<<<<<<< HEAD
            field=models.DateField(default=datetime.date(2023, 7, 8), verbose_name='Data do vencimento'),
=======
            field=models.DateField(
                default=datetime.date(2023, 7, 3), verbose_name='Data do vencimento'
            ),
>>>>>>> 0b41b9008ba417b31db9cf1b88ad446e9eb9c078
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
<<<<<<< HEAD
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensal', max_length=255, verbose_name='Nome do plano'),
=======
            field=models.CharField(
                choices=[
                    ('Mensal', 'Mensal'),
                    ('Trimestral', 'Trimestral'),
                    ('Semestral', 'Semestral'),
                    ('Anual', 'Anual'),
                ],
                default='Mensal',
                max_length=255,
                verbose_name='Nome do plano',
            ),
>>>>>>> 0b41b9008ba417b31db9cf1b88ad446e9eb9c078
        ),
    ]
