# Generated by Django 5.0.12 on 2025-05-13 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_dadosbancarios_wpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaowpp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date, verbose_name='Data de adesão'),
        ),
    ]
