# Generated by Django 4.2 on 2023-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0003_alter_plano_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plano",
            name="nome",
            field=models.CharField(
                choices=[
                    ("Mensal", "Mensal"),
                    ("Semestral", "Semestral"),
                    ("Anual", "Anual"),
                ],
                default="Mensal",
                max_length=255,
                verbose_name="Nome do plano",
            ),
        ),
    ]
