# Generated by Django 4.2 on 2023-04-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0004_alter_plano_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planoindicacao",
            name="tipo_plano",
            field=models.CharField(
                choices=[
                    ("desconto", "Desconto na mensalidade"),
                    ("dinheiro", "Valor em dinheiro"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="ContaDoAplicativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "device_key",
                    models.CharField(max_length=255, unique=True, verbose_name="Senha"),
                ),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicativos",
                        to="cadastros.sistema",
                        verbose_name="Aplicativo",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conta_aplicativo",
                        to="cadastros.cliente",
                    ),
                ),
            ],
        ),
    ]
