# Generated by Django 5.0.12 on 2025-05-17 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_cliente_data_adesao_dominios_dns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dominios_dns',
            new_name='DominiosDNS',
        ),
    ]
