# Generated by Django 5.0.12 on 2025-05-17 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_rename_dominios_dns_dominiosdns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominiosdns',
            name='servidor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastros.servidor'),
            preserve_default=False,
        ),
    ]
