# Generated by Django 4.2 on 2023-04-18 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0005_alter_planoindicacao_tipo_plano_contadoaplicativo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sistema",
            new_name="Aplicativo",
        ),
    ]
