# Generated by Django 5.0.12 on 2025-05-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_dominiosdns_servidor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominiosdns',
            name='data_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
