# Generated by Django 5.0.12 on 2025-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_dominiosdns_data_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominiosdns',
            name='data_offline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dominiosdns',
            name='data_ultima_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
