# Generated by Django 5.0.12 on 2025-05-18 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_dominiosdns_acesso_canais'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanaisTS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('ativo', models.BooleanField(default=True)),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.dominiosdns')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.servidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canal TS',
                'verbose_name_plural': 'Canais TS',
            },
        ),
    ]
