# Generated by Django 4.2 on 2023-04-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0010_alter_servidor_logotipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servidor",
            name="logotipo",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
