# Generated by Django 4.2 on 2023-04-22 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastros", "0012_alter_servidor_logotipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="data_adesao",
            field=models.DateField(
                default=datetime.date(2023, 4, 22), verbose_name="Data de adesão"
            ),
        ),
        migrations.AlterField(
            model_name="mensalidade",
            name="dt_vencimento",
            field=models.DateField(
                default=datetime.date(2023, 5, 22), verbose_name="Data de vencimento"
            ),
        ),
    ]
