# Generated by Django 5.0.12 on 2025-05-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_remove_canaists_dominio_alter_canaists_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CanaisTS',
        ),
    ]
