# Generated by Django 5.0.12 on 2025-05-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_delete_canaists'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominiosdns',
            name='data_envio_alerta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
