# Generated by Django 5.0.12 on 2025-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_dominiosdns_data_envio_alerta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dominiosdns',
            old_name='ativo',
            new_name='monitorado',
        ),
        migrations.AddField(
            model_name='dominiosdns',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20),
        ),
    ]
