# Generated by Django 5.0.12 on 2025-06-04 09:12

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_rename_ativo_dominiosdns_monitorado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominiosdns',
            name='dominio',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='nome',
            field=models.CharField(choices=[('desconto', 'Desconto por Indicação'), ('dinheiro', 'Bônus por Indicações'), ('anuidade', 'Bônus por Anuidade')], max_length=255),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='tipo_plano',
            field=models.CharField(choices=[('desconto', 'Desconto por Indicação'), ('dinheiro', 'Bônus por Indicações'), ('anuidade', 'Bônus por Anuidade')], max_length=255),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor para desconto ou bonificação'),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='valor_minimo_mensalidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor mínimo a ser mantido na mensalidade'),
        ),
        migrations.AlterUniqueTogether(
            name='planoindicacao',
            unique_together={('usuario', 'tipo_plano')},
        ),
    ]
