# Generated by Django 4.2 on 2023-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0016_cliente_notas_alter_cliente_data_adesao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='dt_cancelamento',
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name='Data do cancelamento'
            ),
        ),
    ]
