# Generated by Django 5.0.12 on 2025-06-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_alter_dominiosdns_dominio_alter_planoindicacao_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='isencao_anuidade',
            field=models.BooleanField(default=False, verbose_name='Isenção por bônus anuidade'),
        ),
    ]
