# Generated by Django 5.0.12 on 2025-06-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_planoindicacao_status_alter_planoindicacao_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioenvios',
            name='nome',
            field=models.CharField(choices=[('mensalidades_a_vencer', 'Notificação de vencimentos'), ('obter_mensalidades_vencidas', 'Notificação de atrasos no pagamento')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horarioenvios',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='horarioenvios',
            name='tipo_envio',
            field=models.CharField(choices=[('mensalidades_a_vencer', 'Notificação de vencimentos'), ('obter_mensalidades_vencidas', 'Notificação de atrasos no pagamento')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
