# Generated by Django 5.0.12 on 2025-06-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_horarioenvios_nome_horarioenvios_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioenvios',
            name='ultimo_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioenvios',
            name='nome',
            field=models.CharField(choices=[('mensalidades_a_vencer', 'Notificação de vencimentos'), ('obter_mensalidades_vencidas', 'Notificação de atrasos')], max_length=255),
        ),
        migrations.AlterField(
            model_name='horarioenvios',
            name='tipo_envio',
            field=models.CharField(choices=[('mensalidades_a_vencer', 'Notificação de vencimentos'), ('obter_mensalidades_vencidas', 'Notificação de atrasos')], max_length=255),
        ),
    ]
