# Generated by Django 4.2 on 2023-05-02 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0022_alter_cliente_data_adesao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoindicacao',
            name='nome',
        ),
    ]
