# Generated by Django 4.2 on 2023-05-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0024_alter_cliente_data_adesao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadoaplicativo',
            name='device_id',
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True, verbose_name='ID'
            ),
        ),
    ]
