# Generated by Django 5.0.3 on 2024-08-14 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0025_mensalidade_notificacao_wpp1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='dt_notif_wpp1',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data envio notificação PROMO'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2024, 9, 13), verbose_name='Data do vencimento'),
        ),
    ]
