# Generated by Django 4.2 on 2023-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0025_alter_contadoaplicativo_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='contadoaplicativo',
            name='device_id',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='ID'
            ),
        ),
        migrations.AlterField(
            model_name='contadoaplicativo',
            name='device_key',
            field=models.CharField(max_length=255, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='contadoaplicativo',
            name='email',
            field=models.EmailField(
                blank=True, max_length=255, null=True, verbose_name='E-mail'
            ),
        ),
    ]
