# Generated by Django 4.2 on 2023-05-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0026_alter_cliente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadoaplicativo',
            name='device_key',
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name='Senha'
            ),
        ),
    ]
