# Generated by Django 5.0.3 on 2024-09-16 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_cliente_nao_enviar_msgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='recebeu_pix_indicacao',
            field=models.BooleanField(default=False, verbose_name='PIX R$50'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2024, 10, 15), verbose_name='Data do vencimento'),
        ),
    ]
