# Generated by Django 4.2.25 on 2025-10-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0028_userprofile_email_on_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_tentado', models.CharField(blank=True, help_text='Username que foi tentado no login (útil para logins falhados)', max_length=150)),
                ('ip', models.GenericIPAddressField(blank=True, help_text='Endereço IPv4 do cliente', null=True, protocol='IPv4')),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent do navegador/dispositivo', max_length=500)),
                ('login_method', models.CharField(choices=[('password', 'Senha'), ('2fa', '2FA'), ('backup_code', 'Código de Backup')], default='password', help_text='Método usado para fazer login', max_length=20)),
                ('success', models.BooleanField(default=True, help_text='Se o login foi bem-sucedido')),
                ('failure_reason', models.CharField(blank=True, help_text='Motivo da falha (se success=False)', max_length=255)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuário que tentou fazer login (null se usuário não encontrado)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Login',
                'verbose_name_plural': 'Logs de Login',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='loginlog_user_created_idx'), models.Index(fields=['-created_at'], name='loginlog_created_idx'), models.Index(fields=['success', '-created_at'], name='loginlog_success_idx'), models.Index(fields=['ip', '-created_at'], name='loginlog_ip_idx')],
            },
        ),
    ]
