# Generated by Django 5.0.3 on 2024-09-16 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_mensalidade_recebeu_pix_indicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2024, 10, 16), verbose_name='Data do vencimento'),
        ),
    ]
