# Generated by Django 4.2 on 2023-05-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cadastros', '0029_alter_cliente_data_adesao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoindicacao',
            name='nome',
            field=models.CharField(default='Desconto na mensalidade', max_length=255),
        ),
    ]
