# Generated by Django 4.2.25 on 2025-10-23 04:33

from django.db import migrations


def ativar_plano_desconto_progressivo(apps, schema_editor):
    """
    Ativa todos os planos 'desconto_progressivo' existentes.

    Isso garante que a nova modalidade apareça no offcanvas de configurações.
    """
    PlanoIndicacao = apps.get_model('cadastros', 'PlanoIndicacao')

    # Atualizar todos os planos desconto_progressivo para ativo=True
    PlanoIndicacao.objects.filter(
        tipo_plano='desconto_progressivo',
        ativo=False
    ).update(ativo=True)


def reverter_ativacao(apps, schema_editor):
    """Reverte a ativação dos planos desconto_progressivo."""
    PlanoIndicacao = apps.get_model('cadastros', 'PlanoIndicacao')

    # Reverter para ativo=False
    PlanoIndicacao.objects.filter(
        tipo_plano='desconto_progressivo'
    ).update(ativo=False)


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_planoindicacao_limite_indicacoes_and_more'),
    ]

    operations = [
        migrations.RunPython(ativar_plano_desconto_progressivo, reverter_ativacao),
    ]
