# Generated by Django 5.0.14 on 2025-05-07 23:13

import cadastros.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0033_cliente_enviado_oferta_promo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoM3U8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('capa', models.URLField()),
                ('temporada', models.IntegerField(blank=True, null=True)),
                ('episodio', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('upload', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Conteúdo M3U8',
                'verbose_name_plural': 'Conteúdos M3U8',
            },
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telas',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-data_adesao']},
        ),
        migrations.AlterModelOptions(
            name='contadoaplicativo',
            options={'verbose_name': 'Conta do Aplicativo', 'verbose_name_plural': 'Contas dos Aplicativos'},
        ),
        migrations.AlterModelOptions(
            name='mensagemenviadawpp',
            options={'verbose_name': 'Mensagem Enviada ao WhatsApp', 'verbose_name_plural': 'Mensagens Enviadas ao WhatsApp'},
        ),
        migrations.AlterModelOptions(
            name='tipos_pgto',
            options={'verbose_name': 'Tipo de Pagamento', 'verbose_name_plural': 'Tipos de Pagamentos'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='aplicativo',
            name='device_has_mac',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento inicial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dadosbancarios',
            name='wpp',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plano',
            name='telas',
            field=models.IntegerField(default=1, verbose_name='Número de telas'),
        ),
        migrations.AddField(
            model_name='planoindicacao',
            name='valor_minimo_mensalidade',
            field=models.DecimalField(decimal_places=2, default=13.99, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor mínimo a ser mantido na mensalidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secrettokenapi',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secrettokenapi',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='horarioenvios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_cancelamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do cancelamento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_notif_wpp1',
            field=models.DateField(blank=True, null=True, verbose_name='Data envio notificação PROMO'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=cadastros.models.default_vencimento, verbose_name='Data do vencimento'),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor para desconto ou bonificação'),
        ),
        migrations.AddIndex(
            model_name='contadoaplicativo',
            index=models.Index(fields=['cliente', 'app'], name='cadastros_c_cliente_d49878_idx'),
        ),
        migrations.AddIndex(
            model_name='contadoaplicativo',
            index=models.Index(fields=['device_id'], name='cadastros_c_device__90d23d_idx'),
        ),
        migrations.AddField(
            model_name='conteudom3u8',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Qtd_tela',
        ),
    ]
