# Generated by Django 5.0.14 on 2025-05-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_conteudom3u8_remove_cliente_telas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_vencimento2',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento inicial'),
        ),
    ]
