# Generated by Django 4.2.25 on 2025-10-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_alter_servidor_nome'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='horarioenvios',
            index=models.Index(fields=['status', 'ativo', 'horario', 'ultimo_envio'], name='horarioenvios_agendados_idx'),
        ),
        migrations.AddIndex(
            model_name='horarioenvios',
            index=models.Index(fields=['usuario', 'tipo_envio'], name='horarioenvios_usuario_tipo_idx'),
        ),
    ]
