# Generated by Django 4.2.1 on 2023-05-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipos_pgto',
            name='nome',
            field=models.CharField(choices=[('PIX', 'PIX'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Boleto', 'Boleto')], default='PIX', max_length=255),
        ),
    ]
