# Generated by Django 4.2.1 on 2023-05-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0036_alter_tipos_pgto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(choices=[('CLUB', 'CLUB'), ('PlayON', 'PlayON'), ('ALPHA', 'ALPHA'), ('SEVEN', 'SEVEN'), ('FIVE', 'FIVE')], max_length=255),
        ),
    ]
