# Generated by Django 4.2.1 on 2023-05-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_alter_servidor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
