# Generated by Django 5.0.14 on 2025-05-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_cliente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_vencimento2',
            new_name='data_vencimento',
        ),
    ]
