# Generated by Django 4.2.25 on 2025-10-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_remove_duplicate_mensagens_wpp'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mensagemenviadawpp',
            constraint=models.UniqueConstraint(fields=('usuario', 'telefone', 'data_envio'), name='unique_msg_por_usuario_telefone_dia'),
        ),
    ]
