# Generated by Django 4.2.1 on 2023-05-11 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_alter_aplicativo_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='servidor',
            name='logotipo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 5, 10), verbose_name='Data de adesão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2023, 6, 9), verbose_name='Data do vencimento'),
        ),
    ]
