# Generated by Django 4.2.1 on 2023-05-12 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_alter_servidor_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=datetime.date(2023, 5, 11), verbose_name='Data de adesão'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2023, 6, 10), verbose_name='Data do vencimento'),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='tipo_plano',
            field=models.CharField(choices=[('desconto', 'Desconto na mensalidade'), ('dinheiro', 'Valor em dinheiro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(choices=[('CLUB', 'CLUB'), ('PlayON', 'PlayON'), ('ALPHA', 'ALPHA'), ('SEVEN', 'SEVEN'), ('FIVE', 'FIVE')], max_length=255),
        ),
    ]
