# Generated by Django 4.2.25 on 2025-11-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0041_alter_useractionlog_acao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_login', models.EmailField(help_text='Email ou username usado para login no painel reseller', max_length=255, verbose_name='Email/Usuário')),
                ('senha_login', models.CharField(help_text='Senha criptografada com Fernet', max_length=500, verbose_name='Senha')),
                ('session_data', models.TextField(blank=True, help_text='JSON contendo cookies e localStorage para reutilização de sessão', verbose_name='Dados de Sessão')),
                ('ultimo_login', models.DateTimeField(blank=True, help_text='Data/hora do último login manual bem-sucedido', null=True, verbose_name='Último Login')),
                ('sessao_valida', models.BooleanField(default=False, help_text='Indica se a sessão armazenada ainda está ativa', verbose_name='Sessão Válida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('aplicativo', models.ForeignKey(help_text='Aplicativo/plataforma do reseller (ex: DreamTV, NetFlox)', on_delete=django.db.models.deletion.CASCADE, related_name='contas_reseller', to='cadastros.aplicativo')),
                ('usuario', models.ForeignKey(help_text='Usuário proprietário desta conta reseller', on_delete=django.db.models.deletion.CASCADE, related_name='contas_reseller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta de Reseller',
                'verbose_name_plural': 'Contas de Reseller',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='TarefaMigracaoDNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_migracao', models.CharField(choices=[('todos', 'Todos os Dispositivos'), ('especifico', 'Dispositivo Específico')], default='especifico', help_text='Se migração é para todos os dispositivos ou apenas um específico', max_length=20, verbose_name='Tipo de Migração')),
                ('mac_alvo', models.CharField(blank=True, help_text='MAC Address do dispositivo específico (se tipo_migracao=especifico)', max_length=100, verbose_name='MAC Alvo')),
                ('dominio_origem_url', models.URLField(help_text='URL do domínio DNS atual (antes da migração)', max_length=500, verbose_name='Domínio DNS Origem')),
                ('dominio_destino_url', models.URLField(help_text='URL do domínio DNS novo (após a migração)', max_length=500, verbose_name='Domínio DNS Destino')),
                ('status', models.CharField(choices=[('aguardando_login', 'Aguardando Login'), ('iniciando', 'Iniciando'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('erro_login', 'Erro no Login'), ('cancelada', 'Cancelada')], db_index=True, default='iniciando', max_length=20)),
                ('total_dispositivos', models.IntegerField(default=0, help_text='Quantidade total de dispositivos a serem migrados', verbose_name='Total de Dispositivos')),
                ('processados', models.IntegerField(default=0, help_text='Quantidade de dispositivos já processados', verbose_name='Dispositivos Processados')),
                ('sucessos', models.IntegerField(default=0, help_text='Quantidade de dispositivos migrados com sucesso', verbose_name='Sucessos')),
                ('falhas', models.IntegerField(default=0, help_text='Quantidade de dispositivos com erro na migração', verbose_name='Falhas')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('iniciada_em', models.DateTimeField(blank=True, help_text='Quando a execução efetivamente começou', null=True, verbose_name='Data de Início')),
                ('concluida_em', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('erro_geral', models.TextField(blank=True, help_text='Mensagem de erro que impediu a execução da tarefa inteira', verbose_name='Erro Geral')),
                ('aplicativo', models.ForeignKey(help_text='Aplicativo/plataforma onde a migração será executada', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_migracao_dns', to='cadastros.aplicativo')),
                ('conta_reseller', models.ForeignKey(blank=True, help_text='Conta reseller usada para executar a migração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_migracao', to='cadastros.contareseller')),
                ('usuario', models.ForeignKey(help_text='Usuário que iniciou a migração', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_migracao_dns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa de Migração DNS',
                'verbose_name_plural': 'Tarefas de Migração DNS',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='DispositivoMigracaoDNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Identificador do dispositivo (MAC Address)', max_length=100, verbose_name='MAC Address')),
                ('nome_dispositivo', models.CharField(blank=True, help_text='Nome ou comentário do dispositivo no painel reseller', max_length=255, verbose_name='Nome/Comentário')),
                ('dns_encontrado', models.URLField(blank=True, help_text='URL do DNS que estava configurada no painel antes da migração', max_length=500, verbose_name='DNS Encontrado')),
                ('dns_atualizado', models.URLField(blank=True, help_text='URL do DNS que foi configurada após a migração', max_length=500, verbose_name='DNS Atualizado')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('pulado', 'Pulado')], db_index=True, default='pendente', max_length=20)),
                ('mensagem_erro', models.TextField(blank=True, help_text='Detalhes do erro ocorrido (se status=erro)', verbose_name='Mensagem de Erro')),
                ('processado_em', models.DateTimeField(blank=True, help_text='Quando este dispositivo foi processado', null=True, verbose_name='Data de Processamento')),
                ('tarefa', models.ForeignKey(help_text='Tarefa de migração à qual este dispositivo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='cadastros.tarefamigracaodns')),
            ],
            options={
                'verbose_name': 'Dispositivo em Migração',
                'verbose_name_plural': 'Dispositivos em Migração',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='tarefamigracaodns',
            index=models.Index(fields=['usuario', '-criada_em'], name='tarefa_dns_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefamigracaodns',
            index=models.Index(fields=['status', '-criada_em'], name='tarefa_dns_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivomigracaodns',
            index=models.Index(fields=['tarefa', 'status'], name='disp_dns_tarefa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contareseller',
            index=models.Index(fields=['usuario', 'aplicativo'], name='conta_reseller_user_app_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contareseller',
            unique_together={('usuario', 'aplicativo')},
        ),
    ]
