# Generated by Django 4.2.25 on 2025-11-03 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0043_rename_dominio_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_headless_mode', models.BooleanField(default=False, help_text='Quando ativado, o navegador Playwright ficará visível durante automações (útil para debug)', verbose_name='Modo Debug (Navegador Visível)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_automacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Configuração de Automação',
                'verbose_name_plural': 'Configurações de Automação',
            },
        ),
    ]
