# Generated by Django 4.2.25 on 2025-11-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0044_configuracaoautomacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamigracaodns',
            name='pulados',
            field=models.IntegerField(default=0, help_text='Quantidade de dispositivos pulados (DNS não corresponde ao domínio origem)', verbose_name='Pulados'),
        ),
    ]
