# Generated by Django 4.2.25 on 2025-11-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0045_add_pulados_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamigracaodns',
            name='etapa_atual',
            field=models.CharField(default='iniciando', help_text='Etapa atual da execução (iniciando, analisando, processando, concluida, cancelada)', max_length=50, verbose_name='Etapa Atual'),
        ),
        migrations.AddField(
            model_name='tarefamigracaodns',
            name='mensagem_progresso',
            field=models.TextField(blank=True, help_text='Mensagem dinâmica exibida durante a execução', verbose_name='Mensagem de Progresso'),
        ),
        migrations.AddField(
            model_name='tarefamigracaodns',
            name='progresso_percentual',
            field=models.IntegerField(default=0, help_text='Percentual de conclusão da tarefa (0-100)', verbose_name='Progresso (%)'),
        ),
    ]
