# Generated by Django - FASE 1: MVP - Controle de Dispositivos

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0049_tarefamigracaodns_cached_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='max_dispositivos',
            field=models.IntegerField(
                default=1,
                help_text='Quantidade máxima recomendada de dispositivos onde o app pode ser instalado',
                verbose_name='Máximo de dispositivos'
            ),
        ),
    ]
