# Generated by Django - FASE 1: MVP - Modelo AssinaturaCliente

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def criar_assinaturas_para_clientes_existentes(apps, schema_editor):
    """
    Backfill: Cria AssinaturaCliente para todos os clientes existentes.

    Para cada cliente existente no sistema, cria uma AssinaturaCliente
    vinculada ao plano atual do cliente.
    """
    Cliente = apps.get_model('cadastros', 'Cliente')
    AssinaturaCliente = apps.get_model('cadastros', 'AssinaturaCliente')

    clientes = Cliente.objects.all()
    assinaturas_criadas = 0

    for cliente in clientes:
        # Verifica se já existe assinatura (por segurança)
        if not AssinaturaCliente.objects.filter(cliente=cliente).exists():
            AssinaturaCliente.objects.create(
                cliente=cliente,
                plano=cliente.plano,
                data_inicio_assinatura=cliente.data_adesao or timezone.now().date(),
                ativo=not cliente.cancelado,
                dispositivos_usados=0  # Inicia em 0, será atualizado por signals futuros
            )
            assinaturas_criadas += 1

    print(f"✓ {assinaturas_criadas} AssinaturaCliente criadas para clientes existentes")


def reverter_assinaturas(apps, schema_editor):
    """
    Reversão: Remove todas as assinaturas criadas.
    """
    AssinaturaCliente = apps.get_model('cadastros', 'AssinaturaCliente')
    count = AssinaturaCliente.objects.count()
    AssinaturaCliente.objects.all().delete()
    print(f"✓ {count} AssinaturaCliente removidas")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0050_add_plano_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio_assinatura', models.DateField(verbose_name='Data de início da assinatura')),
                ('dispositivos_usados', models.IntegerField(default=0, verbose_name='Dispositivos em uso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='cadastros.cliente')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.plano')),
            ],
            options={
                'verbose_name': 'Assinatura de Cliente',
                'verbose_name_plural': 'Assinaturas de Clientes',
                'indexes': [
                    models.Index(fields=['cliente', 'ativo'], name='cadastros_a_cliente_ativo_idx'),
                ],
            },
        ),
        migrations.RunPython(
            criar_assinaturas_para_clientes_existentes,
            reverter_assinaturas
        ),
    ]
