# Generated by Django 4.2.25 on 2025-11-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0051_create_assinatura_cliente'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assinaturacliente',
            new_name='cadastros_a_cliente_3edc24_idx',
            old_name='cadastros_a_cliente_ativo_idx',
        ),
        migrations.AlterField(
            model_name='assinaturacliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assinaturacliente',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='cadastros.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='assinaturacliente',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assinaturacliente',
            name='data_inicio_assinatura',
            field=models.DateField(help_text='Data em que o cliente aderiu ao plano atual', verbose_name='Data de início da assinatura'),
        ),
        migrations.AlterField(
            model_name='assinaturacliente',
            name='dispositivos_usados',
            field=models.IntegerField(default=0, help_text='Quantidade atual de dispositivos cadastrados (informativo)', verbose_name='Dispositivos em uso'),
        ),
        migrations.AlterField(
            model_name='assinaturacliente',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.plano', verbose_name='Plano'),
        ),
    ]
