# Generated by Django 4.2.25 on 2025-11-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0053_alter_plano_max_dispositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='max_contas_app',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Máximo de contas app (TEMPORÁRIO - será removido)'),
        ),
    ]
