# Generated by Django - FASE 1: MVP - Backfill de Contadores de Dispositivos

from django.db import migrations


def atualizar_contadores_dispositivos(apps, schema_editor):
    """
    Backfill: Atualiza contador dispositivos_usados baseado em ContaDoAplicativo existentes.

    Para cada AssinaturaCliente, conta quantos ContaDoAplicativo estão vinculados
    ao cliente e atualiza o campo dispositivos_usados com o valor real.
    """
    AssinaturaCliente = apps.get_model('cadastros', 'AssinaturaCliente')
    ContaDoAplicativo = apps.get_model('cadastros', 'ContaDoAplicativo')

    assinaturas_atualizadas = 0
    total_dispositivos = 0

    for assinatura in AssinaturaCliente.objects.all():
        # Conta dispositivos existentes para este cliente
        count = ContaDoAplicativo.objects.filter(cliente=assinatura.cliente).count()

        # Atualiza contador se diferente
        if assinatura.dispositivos_usados != count:
            assinatura.dispositivos_usados = count
            assinatura.save(update_fields=['dispositivos_usados'])
            assinaturas_atualizadas += 1
            total_dispositivos += count

    print(f"[OK] {assinaturas_atualizadas} AssinaturaCliente atualizadas")
    print(f"[OK] Total de {total_dispositivos} dispositivos contabilizados")


def reverter_contadores(apps, schema_editor):
    """
    Reversão: Zera todos os contadores de dispositivos.
    """
    AssinaturaCliente = apps.get_model('cadastros', 'AssinaturaCliente')

    count = AssinaturaCliente.objects.filter(dispositivos_usados__gt=0).count()
    AssinaturaCliente.objects.all().update(dispositivos_usados=0)

    print(f"[OK] {count} contadores zerados")


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0055_remove_plano_max_contas_app'),
    ]

    operations = [
        migrations.RunPython(
            atualizar_contadores_dispositivos,
            reverter_contadores
        ),
    ]
