# Generated by Django 5.2.8 on 2025-11-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0056_backfill_dispositivos_usados'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='permite_oferta_promocional',
            field=models.BooleanField(default=False, help_text='Define se este plano pode ser oferecido como promoção', verbose_name='Permite oferta promocional'),
        ),
    ]
