# Generated by Django 5.2.8 on 2025-11-24 05:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0057_plano_permite_oferta_promocional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mensalidades', models.IntegerField(help_text='Quantos meses a oferta dura (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Número de Mensalidades')),
                ('mensalidades_restantes', models.IntegerField(help_text='Contador de meses restantes', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Mensalidades Restantes')),
                ('valor_mes_1', models.DecimalField(blank=True, decimal_places=2, help_text='Valor da 1ª mensalidade', max_digits=7, null=True, verbose_name='Valor Mês 1')),
                ('valor_mes_2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor Mês 2')),
                ('valor_mes_3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor Mês 3')),
                ('valor_mes_4', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor Mês 4')),
                ('valor_mes_5', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor Mês 5')),
                ('valor_mes_6', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Valor Mês 6')),
                ('data_inicio', models.DateField(default=datetime.date.today, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_promocionais', to='cadastros.cliente', verbose_name='Cliente')),
                ('plano_oferta', models.ForeignKey(help_text='Apenas planos marcados como promocionais', limit_choices_to={'permite_oferta_promocional': True}, on_delete=django.db.models.deletion.PROTECT, to='cadastros.plano', verbose_name='Plano Promocional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta Promocional',
                'verbose_name_plural': 'Ofertas Promocionais',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['cliente', 'ativo'], name='cadastros_o_cliente_35dd80_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(mensalidades_restantes__gte=0), name='mensalidades_restantes_nao_negativo')],
            },
        ),
    ]
