# Generated by Django 5.2.8 on 2025-11-24 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0058_ofertapromocional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='permite_oferta_promocional',
        ),
        migrations.AddField(
            model_name='assinaturacliente',
            name='campanha_data_adesao',
            field=models.DateField(blank=True, help_text='Quando o cliente se inscreveu na campanha', null=True, verbose_name='Data de Adesão à Campanha'),
        ),
        migrations.AddField(
            model_name='assinaturacliente',
            name='campanha_duracao_total',
            field=models.IntegerField(blank=True, help_text='Snapshot da duração quando cliente aderiu (usado para calcular progresso)', null=True, verbose_name='Duração Total da Campanha'),
        ),
        migrations.AddField(
            model_name='assinaturacliente',
            name='campanha_mensalidades_pagas',
            field=models.IntegerField(default=0, help_text='Contador de mensalidades pagas durante a campanha', verbose_name='Mensalidades Pagas (Campanha)'),
        ),
        migrations.AddField(
            model_name='assinaturacliente',
            name='campanha_plano_id',
            field=models.IntegerField(blank=True, help_text='ID do plano cuja campanha o cliente está participando (permite rastreamento em troca de plano)', null=True, verbose_name='ID do Plano da Campanha'),
        ),
        migrations.AddField(
            model_name='assinaturacliente',
            name='em_campanha',
            field=models.BooleanField(default=False, help_text='Cliente está participando de uma campanha promocional', verbose_name='Em Campanha'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_ativa',
            field=models.BooleanField(default=False, help_text='Define se este plano possui uma campanha promocional ativa', verbose_name='Campanha Ativa'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_data_fim',
            field=models.DateField(blank=True, help_text='Data de fim da validade (controla adesão de NOVOS clientes)', null=True, verbose_name='Campanha - Data Fim'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_data_inicio',
            field=models.DateField(blank=True, help_text='Data de início da validade (controla adesão de NOVOS clientes)', null=True, verbose_name='Campanha - Data Início'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_duracao_meses',
            field=models.IntegerField(blank=True, help_text='Quantos meses a campanha dura para clientes inscritos (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Campanha - Duração (meses)'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_tipo',
            field=models.CharField(blank=True, choices=[('FIXO', 'Desconto Fixo'), ('PERSONALIZADO', 'Desconto Personalizado')], help_text='Tipo de desconto da campanha', max_length=20, null=True, verbose_name='Tipo de Campanha'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo da mensalidade durante a campanha (DESCONTO_FIXO)', max_digits=7, null=True, verbose_name='Campanha - Valor Fixo'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_1',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da 1ª mensalidade (DESCONTO_PERSONALIZADO)', max_digits=7, null=True, verbose_name='Campanha - Valor Mês 1'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 2'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 3'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 4'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 5'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 6'),
        ),
    ]
