# Generated by Django 5.2.8 on 2025-11-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0059_remove_plano_permite_oferta_promocional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinaturacliente',
            name='campanha_plano_id',
        ),
    ]
