# Generated by Django 5.2.8 on 2025-11-25 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0061_mensalidade_dados_historicos_verificados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadoaplicativo',
            name='dispositivo',
            field=models.ForeignKey(blank=True, help_text='Em qual dispositivo esta conta está instalada', null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.dispositivo', verbose_name='Tipo de Dispositivo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dispositivo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.dispositivo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sistema',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.aplicativo'),
        ),
    ]
