# Generated by Django 5.2.8 on 2025-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0062_contadoaplicativo_dispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contadoaplicativo',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='Define esta conta como principal. Os dados desta conta sincronizam com os campos Dispositivo e Aplicativo do cliente.', verbose_name='Conta Principal'),
        ),
    ]
