# Generated by Django 5.2.8 on 2025-12-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0066_tarefaenvio_historicoexecucaotarefa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaenvio',
            name='periodo_mes',
            field=models.CharField(choices=[('', 'Selecione o período'), ('1-10', 'Dias 1 a 10'), ('11-20', 'Dias 11 a 20'), ('21-31', 'Dias 21 a 31'), ('1-15', 'Primeira quinzena (1-15)'), ('16-31', 'Segunda quinzena (16-31)'), ('todos', 'Todos os dias do mês')], help_text='Intervalo de dias do mês para execução', max_length=10, verbose_name='Período do Mês'),
        ),
    ]
