# Generated by Django 5.2.8 on 2025-12-02 22:53

from django.db import migrations


def criar_instituicoes_iniciais(apps, schema_editor):
    """
    Cria as instituições bancárias iniciais com integração API.
    Efi Bank e Mercado Pago vêm pré-cadastrados.
    """
    InstituicaoBancaria = apps.get_model('cadastros', 'InstituicaoBancaria')

    # Criar Efi Bank (antiga Gerencianet)
    InstituicaoBancaria.objects.get_or_create(
        nome='Efi Bank',
        defaults={
            'tipo_integracao': 'efi_bank',
            'ativo': True,
        }
    )

    # Criar Mercado Pago
    InstituicaoBancaria.objects.get_or_create(
        nome='Mercado Pago',
        defaults={
            'tipo_integracao': 'mercado_pago',
            'ativo': True,
        }
    )


def remover_instituicoes_iniciais(apps, schema_editor):
    """
    Remove as instituições bancárias iniciais (rollback).
    """
    InstituicaoBancaria = apps.get_model('cadastros', 'InstituicaoBancaria')
    InstituicaoBancaria.objects.filter(
        nome__in=['Efi Bank', 'Mercado Pago']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0069_integracao_bancaria'),
    ]

    operations = [
        migrations.RunPython(
            criar_instituicoes_iniciais,
            remover_instituicoes_iniciais,
        ),
    ]
