# Generated by Django 5.2.8 on 2025-12-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0070_instituicoes_iniciais'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 10'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 11'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 12'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 7'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 8'),
        ),
        migrations.AddField(
            model_name='plano',
            name='campanha_valor_mes_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Campanha - Valor Mês 9'),
        ),
    ]
