# Generated by Django 5.2.8 on 2025-12-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0071_campanha_valor_meses_7_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaowpp',
            name='reject_call_enabled',
            field=models.BooleanField(default=True, verbose_name='Rejeitar chamadas automaticamente'),
        ),
        migrations.AddField(
            model_name='sessaowpp',
            name='reject_call_horario_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário fim (rejeição ativa)'),
        ),
        migrations.AddField(
            model_name='sessaowpp',
            name='reject_call_horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário início (rejeição ativa)'),
        ),
    ]
