# Generated by Django 5.0.3 on 2024-04-20 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_alter_cliente_data_adesao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_adesao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de adesão'),
        ),
    ]
