# Generated by Django 5.0.12 on 2025-03-24 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0032_alter_mensalidade_dt_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enviado_oferta_promo',
            field=models.BooleanField(default=False, verbose_name='Oferta PROMO'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=datetime.date(2025, 4, 23), verbose_name='Data do vencimento'),
        ),
    ]
