# Generated by Django 5.0.14 on 2025-05-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_remove_cliente_data_vencimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
