# Generated by Django 5.0.14 on 2025-05-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='wpp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
