# Generated by Django 5.0.12 on 2025-05-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0008_dominiosdns_data_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominiosdns',
            name='acesso_canais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
