# Generated by Django 5.0.12 on 2025-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0010_canaists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canaists',
            name='nome',
        ),
        migrations.AddField(
            model_name='canaists',
            name='data_offline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canaists',
            name='data_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canaists',
            name='data_ultima_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
