# Generated by Django 5.0.12 on 2025-05-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0011_remove_canaists_nome_canaists_data_offline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canaists',
            name='nome',
            field=models.CharField(default='Canal teste', max_length=255),
            preserve_default=False,
        ),
    ]
