# Generated by Django 5.0.12 on 2025-06-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0018_mensalidade_isencao_anuidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoindicacao',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Visível para o template?'),
        ),
    ]
