# Generated by Django 4.2.20 on 2025-10-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0027_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_on_login',
            field=models.BooleanField(default=False, verbose_name='Notificar por email em novos logins'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_on_password_change',
            field=models.BooleanField(default=True, verbose_name='Notificar por email alterações de senha'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_on_profile_change',
            field=models.BooleanField(default=True, verbose_name='Notificar por email alterações no perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_public',
            field=models.BooleanField(default=False, verbose_name='Perfil público'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_email',
            field=models.BooleanField(default=False, verbose_name='Mostrar email publicamente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Mostrar telefone publicamente'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_statistics',
            field=models.BooleanField(default=True, verbose_name='Mostrar estatísticas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='light', max_length=10, verbose_name='Tema preferido'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, null=True, verbose_name='Códigos de backup 2FA'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA ativado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Chave secreta 2FA'),
        ),
    ]
