# Generated by Django 4.2.25 on 2025-10-24 23:26

import nossopainel.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nossopainel', '0033_ativar_plano_desconto_progressivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='imagem_admin',
            field=models.ImageField(blank=True, help_text='Imagem padrão do servidor (adminuser). Tamanho máximo: 5MB. Formatos: JPG, PNG, GIF, WEBP', null=True, upload_to=nossopainel.models.servidor_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.CreateModel(
            name='ServidorImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(help_text='Imagem personalizada do servidor. Tamanho máximo: 5MB. Formatos: JPG, PNG, GIF, WEBP', upload_to=nossopainel.models.servidor_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens_customizadas', to='nossopainel.servidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem de Servidor',
                'verbose_name_plural': 'Imagens de Servidores',
                'indexes': [models.Index(fields=['servidor', 'usuario'], name='cadastros_s_servido_fd3a6b_idx')],
                'unique_together': {('servidor', 'usuario')},
            },
        ),
    ]
