# Generated by Django 4.2.25 on 2025-10-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0034_servidor_imagem_admin_servidorimagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(choices=[('CLUB', 'CLUB'), ('PLAY', 'PLAY'), ('PlayON', 'PlayON'), ('ALPHA', 'ALPHA'), ('SEVEN', 'SEVEN'), ('FIVE', 'FIVE'), ('GF', 'GF'), ('WAREZ', 'WAREZ')], max_length=255),
        ),
    ]
