# Generated by Django 4.2.25 on 2025-10-30 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nossopainel', '0036_horarioenvios_horarioenvios_agendados_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaPromocionalEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('numero_oferta', models.IntegerField(choices=[(1, 'Primeira Oferta'), (2, 'Segunda Oferta'), (3, 'Terceira Oferta')], help_text='Sequência da oferta (1, 2 ou 3)', verbose_name='Número da Oferta')),
                ('dias_apos_cancelamento', models.IntegerField(help_text='Quantidade de dias após o cancelamento (60, 240 ou 420)', verbose_name='Dias Após Cancelamento')),
                ('data_cancelamento_ref', models.DateField(help_text='Data de cancelamento do cliente no momento do envio', verbose_name='Data de Cancelamento (Referência)')),
                ('mensagem_enviada', models.TextField(blank=True, verbose_name='Mensagem Enviada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas_enviadas', to='nossopainel.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oferta Promocional Enviada',
                'verbose_name_plural': 'Ofertas Promocionais Enviadas',
                'ordering': ['-data_envio'],
                'indexes': [models.Index(fields=['cliente', '-data_envio'], name='oferta_cliente_idx'), models.Index(fields=['usuario', '-data_envio'], name='oferta_usuario_idx'), models.Index(fields=['numero_oferta'], name='oferta_numero_idx')],
            },
        ),
    ]
