# Generated by Django 4.2.25 on 2025-10-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0040_add_unique_constraint_mensagem_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlog',
            name='acao',
            field=models.CharField(choices=[('create', 'Criação'), ('update', 'Atualização'), ('delete', 'Exclusão'), ('import', 'Importação'), ('cancel', 'Cancelamento'), ('reactivate', 'Reativação'), ('payment', 'Pagamento'), ('migration', 'Migração'), ('other', 'Ação')], default='other', max_length=32),
        ),
    ]
