# Generated by Django 4.2.25 on 2025-11-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0047_remove_capsolver_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareseller',
            name='login_progresso',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Não iniciado'),
                    ('conectando', 'Conectando ao painel'),
                    ('pagina_carregada', 'Página carregada'),
                    ('resolvendo_captcha', 'Resolvendo reCAPTCHA'),
                    ('captcha_resolvido', 'reCAPTCHA resolvido'),
                    ('validando', 'Validando credenciais'),
                    ('concluido', 'Login concluído'),
                    ('erro', 'Erro no login'),
                ],
                default='',
                help_text='Etapa atual do processo de login automático',
                max_length=50,
                verbose_name='Progresso do Login',
            ),
        ),
    ]
