# Generated by Django 4.2.25 on 2025-11-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0048_contareseller_login_progresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefamigracaodns',
            name='cached_devices',
            field=models.TextField(blank=True, help_text='JSON temporário com devices do frontend (evita chamadas à API)', null=True, verbose_name='Cache de Devices'),
        ),
    ]
