# Generated by Django 4.2.25 on 2025-11-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0052_rename_cadastros_a_cliente_ativo_idx_cadastros_a_cliente_3edc24_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='max_dispositivos',
            field=models.IntegerField(default=1, help_text='Quantidade máxima de dispositivos (sempre igual ao número de telas)', verbose_name='Máximo de dispositivos'),
        ),
    ]
