# Generated by Django 4.2.25 on 2025-11-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0054_plano_max_contas_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='max_contas_app',
        ),
    ]
