# Generated by Django 5.2.8 on 2025-11-25 00:57

from decimal import Decimal
from django.db import migrations, models


def backfill_mensalidades_historicas(apps, schema_editor):
    """
    Preenche dados históricos de mensalidades antigas com estimativa inteligente.

    Estratégia:
    1. Marca todas mensalidades existentes como dados_historicos_verificados=False (estimativa)
    2. Preenche valor_base_plano com valor atual do plano do cliente
    3. Se valor < valor_base_plano, calcula diferença e marca como desconto
    4. Por segurança, considera desconto como progressivo (não temos certeza se era campanha)
    """
    Mensalidade = apps.get_model('nossopainel', 'Mensalidade')

    mensalidades_atualizadas = 0
    total_mensalidades = Mensalidade.objects.count()

    print(f"\n[Backfill] Processando {total_mensalidades} mensalidades existentes...")

    for mensalidade in Mensalidade.objects.select_related('cliente__plano').iterator(chunk_size=500):
        try:
            cliente = mensalidade.cliente
            plano_atual = cliente.plano

            # Marcar como dados não verificados (estimativa)
            mensalidade.dados_historicos_verificados = False

            # Preencher valor_base_plano com valor atual do plano
            mensalidade.valor_base_plano = plano_atual.valor

            # Calcular diferença entre valor do plano e valor da mensalidade
            if mensalidade.valor < plano_atual.valor:
                diferenca = plano_atual.valor - mensalidade.valor

                # Considerar como desconto progressivo por segurança
                # (não sabemos se era campanha ou desconto progressivo)
                mensalidade.desconto_progressivo = diferenca
                mensalidade.desconto_campanha = Decimal("0.00")
                mensalidade.gerada_em_campanha = False
            else:
                # Valor integral do plano (sem desconto)
                mensalidade.desconto_progressivo = Decimal("0.00")
                mensalidade.desconto_campanha = Decimal("0.00")
                mensalidade.gerada_em_campanha = False

            mensalidade.save(update_fields=[
                'dados_historicos_verificados',
                'valor_base_plano',
                'desconto_campanha',
                'desconto_progressivo',
                'gerada_em_campanha'
            ])

            mensalidades_atualizadas += 1

            # Progress feedback a cada 100 registros
            if mensalidades_atualizadas % 100 == 0:
                print(f"[Backfill] Processadas {mensalidades_atualizadas}/{total_mensalidades}...")

        except Exception as e:
            print(f"[Backfill] Erro ao processar mensalidade ID {mensalidade.id}: {e}")
            continue

    print(f"[Backfill] OK - {mensalidades_atualizadas} mensalidades atualizadas com sucesso")
    print(f"[Backfill] AVISO - Dados marcados como 'estimativa' (dados_historicos_verificados=False)")
    print(f"[Backfill] INFO - Novas mensalidades terao rastreamento preciso")


def reverter_backfill(apps, schema_editor):
    """
    Reversão: Limpa os dados de backfill.
    """
    Mensalidade = apps.get_model('nossopainel', 'Mensalidade')

    count = Mensalidade.objects.count()

    Mensalidade.objects.all().update(
        dados_historicos_verificados=True,
        valor_base_plano=None,
        desconto_campanha=Decimal("0.00"),
        desconto_progressivo=Decimal("0.00"),
        gerada_em_campanha=False,
        tipo_campanha=None,
        numero_mes_campanha=None
    )

    print(f"[Reversao] OK - {count} mensalidades revertidas ao estado original")


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0060_remove_campanha_plano_id'),
    ]

    operations = [
        # 1. Adicionar campos
        migrations.AddField(
            model_name='mensalidade',
            name='dados_historicos_verificados',
            field=models.BooleanField(default=True, help_text='False = dados estimados (mensalidades antigas). True = dados precisos (mensalidades novas)', verbose_name='Dados Históricos Verificados'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='desconto_campanha',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto aplicado por campanha promocional', max_digits=7, verbose_name='Desconto de Campanha'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='desconto_progressivo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de desconto aplicado por indicações progressivas', max_digits=7, verbose_name='Desconto Progressivo'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='gerada_em_campanha',
            field=models.BooleanField(default=False, help_text='Indica se esta mensalidade foi gerada durante uma campanha promocional', verbose_name='Gerada em Campanha'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='numero_mes_campanha',
            field=models.IntegerField(blank=True, help_text='Qual mês/pagamento da campanha esta mensalidade representa (1, 2, 3...)', null=True, verbose_name='Número do Mês na Campanha'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='tipo_campanha',
            field=models.CharField(blank=True, help_text='FIXO ou PERSONALIZADO (se gerada em campanha)', max_length=20, null=True, verbose_name='Tipo de Campanha'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='valor_base_plano',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor original do plano no momento da criação (antes de descontos)', max_digits=7, null=True, verbose_name='Valor Base do Plano'),
        ),

        # 2. Backfill inteligente dos dados históricos
        migrations.RunPython(
            backfill_mensalidades_historicas,
            reverter_backfill
        ),
    ]
