# Generated by Django 5.2.8 on 2025-11-25 19:35

from django.db import migrations


def marcar_primeira_conta_como_principal(apps, schema_editor):
    """
    Marca a primeira conta de cada cliente como principal.
    Sincroniza os campos Cliente.dispositivo e Cliente.sistema com a primeira conta.
    """
    Cliente = apps.get_model('nossopainel', 'Cliente')
    ContaDoAplicativo = apps.get_model('nossopainel', 'ContaDoAplicativo')

    for cliente in Cliente.objects.all():
        # Busca a primeira conta do cliente
        primeira_conta = ContaDoAplicativo.objects.filter(cliente=cliente).order_by('id').first()

        if primeira_conta:
            # Marca como principal
            primeira_conta.is_principal = True
            primeira_conta.save(update_fields=['is_principal'])

            # Sincroniza com o Cliente (se a conta tiver dispositivo e app)
            if primeira_conta.dispositivo and primeira_conta.app:
                cliente.dispositivo = primeira_conta.dispositivo
                cliente.sistema = primeira_conta.app
                cliente.save(update_fields=['dispositivo', 'sistema'])


def reverter_marcacao(apps, schema_editor):
    """Reverte a marcação de contas principais."""
    ContaDoAplicativo = apps.get_model('nossopainel', 'ContaDoAplicativo')
    ContaDoAplicativo.objects.all().update(is_principal=False)


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0063_contadoaplicativo_is_principal'),
    ]

    operations = [
        migrations.RunPython(marcar_primeira_conta_como_principal, reverter_marcacao),
    ]
