# Generated by Django 5.2.8 on 2025-12-02 02:55

import nossopainel.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0065_add_user_fk_to_sessaowpp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador da tarefa (ex: "Promoção Natal Ativos")', max_length=100, verbose_name='Nome da Tarefa')),
                ('tipo_envio', models.CharField(choices=[('ativos', 'Clientes Ativos'), ('cancelados', 'Clientes Cancelados'), ('avulso', 'Leads (Avulso)')], help_text='Público-alvo do envio', max_length=20, verbose_name='Tipo de Envio')),
                ('dias_semana', models.JSONField(default=list, help_text='Lista de dias da semana para execução (0=Segunda, 6=Domingo)', verbose_name='Dias da Semana')),
                ('periodo_mes', models.CharField(choices=[('1-10', 'Dias 1 a 10'), ('11-20', 'Dias 11 a 20'), ('21-31', 'Dias 21 a 31'), ('1-15', 'Primeira quinzena (1-15)'), ('16-31', 'Segunda quinzena (16-31)'), ('todos', 'Todos os dias do mês')], default='todos', help_text='Intervalo de dias do mês para execução', max_length=10, verbose_name='Período do Mês')),
                ('horario', models.TimeField(help_text='Horário do dia para início dos envios', verbose_name='Horário')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem a ser enviada (opcional). Max 5MB. Formatos: JPG, PNG, GIF, WEBP', null=True, upload_to=nossopainel.models.tarefa_envio_imagem_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagem')),
                ('mensagem', models.TextField(help_text='Texto da mensagem (suporta negrito e itálico)', verbose_name='Mensagem')),
                ('mensagem_plaintext', models.TextField(blank=True, help_text='Versão plaintext da mensagem com formatação WhatsApp (gerada automaticamente)', verbose_name='Mensagem (Plaintext)')),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, a tarefa não será executada', verbose_name='Ativo')),
                ('ultimo_envio', models.DateTimeField(blank=True, help_text='Data/hora da última execução', null=True, verbose_name='Último Envio')),
                ('total_envios', models.PositiveIntegerField(default=0, help_text='Contador total de mensagens enviadas', verbose_name='Total de Envios')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_envio', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa de Envio',
                'verbose_name_plural': 'Tarefas de Envio',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoExecucaoTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Execução')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro')], max_length=20, verbose_name='Status')),
                ('quantidade_enviada', models.PositiveIntegerField(default=0, verbose_name='Quantidade Enviada')),
                ('quantidade_erros', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Erros')),
                ('detalhes', models.TextField(blank=True, help_text='JSON com detalhes da execução e eventuais erros', verbose_name='Detalhes')),
                ('duracao_segundos', models.PositiveIntegerField(default=0, verbose_name='Duração (segundos)')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='nossopainel.tarefaenvio', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Histórico de Execução',
                'verbose_name_plural': 'Históricos de Execução',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.AddIndex(
            model_name='tarefaenvio',
            index=models.Index(fields=['usuario', 'tipo_envio', 'ativo'], name='tarefa_usr_tipo_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='tarefaenvio',
            index=models.Index(fields=['ativo', 'horario'], name='tarefa_ativo_horario_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoexecucaotarefa',
            index=models.Index(fields=['tarefa', 'data_execucao'], name='hist_tarefa_data_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoexecucaotarefa',
            index=models.Index(fields=['status'], name='hist_status_idx'),
        ),
    ]
