# Generated by Django 5.2.8 on 2025-12-02 04:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0067_tarefa_envio_periodo_obrigatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_envios_por_execucao', models.PositiveIntegerField(default=100, help_text='Máximo de mensagens enviadas por execução de tarefa', verbose_name='Limite de Envios por Execução')),
                ('intervalo_entre_mensagens', models.PositiveIntegerField(default=5, help_text='Segundos de espera entre cada mensagem enviada', verbose_name='Intervalo Entre Mensagens (seg)')),
                ('horario_inicio_permitido', models.TimeField(default='08:00', help_text='Horário mínimo para iniciar envios', verbose_name='Horário Início Permitido')),
                ('horario_fim_permitido', models.TimeField(default='20:00', help_text='Horário máximo para envios', verbose_name='Horário Fim Permitido')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Configuração de Envio',
                'verbose_name_plural': 'Configurações de Envio',
            },
        ),
        migrations.AddField(
            model_name='tarefaenvio',
            name='filtro_cidades',
            field=models.JSONField(blank=True, default=list, help_text='Lista de cidades para filtrar clientes (vazio = todas)', verbose_name='Filtro por Cidades'),
        ),
        migrations.AddField(
            model_name='tarefaenvio',
            name='filtro_estados',
            field=models.JSONField(blank=True, default=list, help_text='Lista de UFs para filtrar clientes (vazio = todos)', verbose_name='Filtro por Estados'),
        ),
        migrations.AddField(
            model_name='tarefaenvio',
            name='pausado_ate',
            field=models.DateTimeField(blank=True, help_text='Data/hora até quando a tarefa está pausada', null=True, verbose_name='Pausado Até'),
        ),
        migrations.CreateModel(
            name='VarianteMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Variante A, Variante B', max_length=50, verbose_name='Nome da Variante')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem alternativa (opcional)', null=True, upload_to='tarefas_envio/variantes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagem')),
                ('mensagem', models.TextField(help_text='Texto alternativo da mensagem', verbose_name='Mensagem')),
                ('mensagem_plaintext', models.TextField(blank=True, help_text='Versão plaintext gerada automaticamente', verbose_name='Mensagem (Plaintext)')),
                ('peso', models.PositiveIntegerField(default=50, help_text='Percentual de envios para esta variante (0-100)', verbose_name='Peso (%)')),
                ('total_envios', models.PositiveIntegerField(default=0, verbose_name='Total de Envios')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='nossopainel.tarefaenvio', verbose_name='Tarefa')),
            ],
            options={
                'verbose_name': 'Variante de Mensagem',
                'verbose_name_plural': 'Variantes de Mensagem',
                'ordering': ['tarefa', 'nome'],
            },
        ),
    ]
