# Generated by Django 5.2.8 on 2025-12-02 22:53

import nossopainel.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0068_add_tarefas_envio_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituicaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Instituição')),
                ('tipo_integracao', models.CharField(choices=[('efi_bank', 'Efi Bank (API)'), ('mercado_pago', 'Mercado Pago (API)'), ('manual', 'Manual (sem API)')], default='manual', max_length=20, verbose_name='Tipo de Integração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Instituição Bancária',
                'verbose_name_plural': 'Instituições Bancárias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_identificacao', models.CharField(help_text='Ex: Minha conta Efi Principal', max_length=100, verbose_name='Nome de Identificação')),
                ('tipo_conta', models.CharField(choices=[('pf', 'Pessoa Física'), ('mei', 'MEI')], default='pf', max_length=10, verbose_name='Tipo de Conta')),
                ('beneficiario', models.CharField(max_length=255, verbose_name='Beneficiário')),
                ('tipo_chave_pix', models.CharField(choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('celular', 'Celular'), ('aleatoria', 'Chave Aleatória')], max_length=50, verbose_name='Tipo de Chave PIX')),
                ('chave_pix', models.CharField(max_length=255, verbose_name='Chave PIX')),
                ('api_client_id', models.CharField(blank=True, help_text='Credencial da API (Efi Bank ou Mercado Pago)', max_length=255, verbose_name='Client ID')),
                ('api_client_secret', models.CharField(blank=True, help_text='Será armazenado de forma segura', max_length=255, verbose_name='Client Secret')),
                ('api_certificado', models.FileField(blank=True, help_text='Obrigatório para Efi Bank', null=True, upload_to=nossopainel.models.certificado_upload_path, verbose_name='Certificado (.p12)')),
                ('api_access_token', models.CharField(blank=True, help_text='Obrigatório para Mercado Pago', max_length=500, verbose_name='Access Token')),
                ('ambiente_sandbox', models.BooleanField(default=True, help_text='Marque para usar ambiente de testes', verbose_name='Ambiente Sandbox')),
                ('limite_mensal', models.DecimalField(blank=True, decimal_places=2, help_text='Limite de recebimento mensal para contas MEI', max_digits=12, null=True, verbose_name='Limite Mensal (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias', to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nossopainel.instituicaobancaria', verbose_name='Instituição')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'chave_pix')},
            },
        ),
        migrations.AddField(
            model_name='tipos_pgto',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, help_text='Conta bancária para recebimento (obrigatório para PIX)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formas_pagamento', to='nossopainel.contabancaria', verbose_name='Conta Bancária'),
        ),
        migrations.AlterUniqueTogether(
            name='tipos_pgto',
            unique_together={('usuario', 'nome', 'conta_bancaria')},
        ),
        migrations.CreateModel(
            name='ClienteContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_bancarias_associadas', to='nossopainel.cliente')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_associados', to='nossopainel.contabancaria')),
            ],
            options={
                'verbose_name': 'Cliente - Conta Bancária',
                'verbose_name_plural': 'Clientes - Contas Bancárias',
                'unique_together': {('cliente', 'conta_bancaria')},
            },
        ),
    ]
