# Generated by Django 5.2.8 on 2025-12-06 02:56

from django.db import migrations, models


def add_reject_call_fields(apps, schema_editor):
    """Adiciona campos reject_call diretamente na tabela cadastros_sessaowpp"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Verifica se coluna já existe
        cursor.execute("PRAGMA table_info(cadastros_sessaowpp)")
        columns = [col[1] for col in cursor.fetchall()]

        if 'reject_call_enabled' not in columns:
            cursor.execute(
                "ALTER TABLE cadastros_sessaowpp ADD COLUMN reject_call_enabled bool DEFAULT 1"
            )
        if 'reject_call_horario_inicio' not in columns:
            cursor.execute(
                "ALTER TABLE cadastros_sessaowpp ADD COLUMN reject_call_horario_inicio time NULL"
            )
        if 'reject_call_horario_fim' not in columns:
            cursor.execute(
                "ALTER TABLE cadastros_sessaowpp ADD COLUMN reject_call_horario_fim time NULL"
            )


def remove_reject_call_fields(apps, schema_editor):
    """Remove não é possível em SQLite - apenas ignora"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0071_campanha_valor_meses_7_12'),
    ]

    operations = [
        # Operação de banco: executa SQL raw para adicionar colunas
        migrations.RunPython(add_reject_call_fields, remove_reject_call_fields),
        # Operação de estado: informa ao Django que os campos existem no modelo
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='sessaowpp',
                    name='reject_call_enabled',
                    field=models.BooleanField(default=True, verbose_name='Rejeitar chamadas automaticamente'),
                ),
                migrations.AddField(
                    model_name='sessaowpp',
                    name='reject_call_horario_inicio',
                    field=models.TimeField(blank=True, null=True, verbose_name='Horário início (rejeição ativa)'),
                ),
                migrations.AddField(
                    model_name='sessaowpp',
                    name='reject_call_horario_fim',
                    field=models.TimeField(blank=True, null=True, verbose_name='Horário fim (rejeição ativa)'),
                ),
            ],
            database_operations=[],  # Já executado pelo RunPython acima
        ),
    ]
