# Generated by Django 5.0.14 on 2025-12-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0073_alter_aplicativo_table_alter_assinaturacliente_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaenvio',
            name='em_execucao',
            field=models.BooleanField(default=False, help_text='Indica se a tarefa está sendo executada no momento', verbose_name='Em Execução'),
        ),
        migrations.AddField(
            model_name='tarefaenvio',
            name='execucao_iniciada_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora do início da execução atual', null=True, verbose_name='Execução Iniciada Em'),
        ),
    ]
