# Generated by Django 5.0.14 on 2025-12-12 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0074_add_tarefa_em_execucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefaenvio',
            name='data_envio_unico',
            field=models.DateField(blank=True, help_text='Data específica para envio único (ignora dias da semana)', null=True, verbose_name='Data do Envio Único'),
        ),
        migrations.AddField(
            model_name='tarefaenvio',
            name='tipo_agendamento',
            field=models.CharField(choices=[('recorrente', 'Recorrente'), ('unico', 'Envio Único')], default='recorrente', help_text='Recorrente: repete nos dias selecionados. Único: executa apenas uma vez na data específica.', max_length=20, verbose_name='Tipo de Agendamento'),
        ),
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome identificador do template', max_length=100, verbose_name='Nome do Template')),
                ('descricao', models.CharField(blank=True, help_text='Descrição breve do template', max_length=255, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('promocao', 'Promoção'), ('lembrete', 'Lembrete'), ('boas_vindas', 'Boas-vindas'), ('cobranca', 'Cobrança'), ('geral', 'Geral')], default='geral', help_text='Categoria para organização', max_length=50, verbose_name='Categoria')),
                ('mensagem_html', models.TextField(help_text='Conteúdo da mensagem com formatação', verbose_name='Mensagem (HTML)')),
                ('imagem', models.ImageField(blank=True, help_text='Imagem associada ao template (opcional)', null=True, upload_to='templates_mensagem/', verbose_name='Imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_mensagem', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'db_table': 'cadastros_templatemensagem',
                'ordering': ['categoria', 'nome'],
            },
        ),
    ]
