# Generated by Django 5.0.14 on 2025-12-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0075_add_template_mensagem_e_tipo_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='api_key',
            field=models.CharField(blank=True, help_text='Token de autenticação (obrigatório para FastDePix - formato: fdpx_...)', max_length=255, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='instituicaobancaria',
            name='tipo_integracao',
            field=models.CharField(choices=[('fastdepix', 'FastDePix (API)'), ('efi_bank', 'Efi Bank (API)'), ('mercado_pago', 'Mercado Pago (API)'), ('manual', 'Manual (sem API)')], default='manual', max_length=20, verbose_name='Tipo de Integração'),
        ),
    ]
