# Generated by Django - Data migration para adicionar FastDePix

from django.db import migrations


def criar_fastdepix(apps, schema_editor):
    """
    Adiciona o FastDePix como instituição bancária com integração API.
    """
    InstituicaoBancaria = apps.get_model('nossopainel', 'InstituicaoBancaria')

    # Criar FastDePix
    InstituicaoBancaria.objects.get_or_create(
        nome='FastDePix',
        defaults={
            'tipo_integracao': 'fastdepix',
            'ativo': True,
        }
    )


def remover_fastdepix(apps, schema_editor):
    """
    Remove o FastDePix (rollback).
    """
    InstituicaoBancaria = apps.get_model('nossopainel', 'InstituicaoBancaria')
    InstituicaoBancaria.objects.filter(nome='FastDePix').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0076_contabancaria_api_key_and_more'),
    ]

    operations = [
        migrations.RunPython(
            criar_fastdepix,
            remover_fastdepix,
        ),
    ]
