# Generated by Django 5.0.14 on 2025-12-17 22:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0077_fastdepix_instituicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaPix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(help_text='ID retornado pela API de pagamento', max_length=255, verbose_name='ID da Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('expired', 'Expirado'), ('cancelled', 'Cancelado'), ('refunded', 'Estornado'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='Status')),
                ('qr_code', models.TextField(blank=True, help_text='Código para gerar imagem do QR Code', verbose_name='QR Code')),
                ('qr_code_base64', models.TextField(blank=True, help_text='Imagem do QR Code em base64', verbose_name='QR Code Base64')),
                ('pix_copia_cola', models.TextField(blank=True, help_text='Código para copiar e colar', verbose_name='PIX Copia e Cola')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField(help_text='Data/hora de expiração da cobrança', verbose_name='Expira em')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('pagador_nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do Pagador')),
                ('pagador_documento', models.CharField(blank=True, max_length=20, verbose_name='CPF/CNPJ do Pagador')),
                ('integracao', models.CharField(help_text='fastdepix, mercado_pago, efi_bank', max_length=50, verbose_name='Integração')),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Resposta completa da API', verbose_name='Resposta Raw')),
                ('webhook_data', models.JSONField(blank=True, default=dict, help_text='Dados recebidos via webhook', verbose_name='Dados Webhook')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_pix', to='nossopainel.cliente', verbose_name='Cliente')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_pix', to='nossopainel.contabancaria', verbose_name='Conta Bancária')),
                ('mensalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_pix', to='nossopainel.mensalidade', verbose_name='Mensalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_pix', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobrança PIX',
                'verbose_name_plural': 'Cobranças PIX',
                'db_table': 'pagamentos_cobranca_pix',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['transaction_id'], name='pagamentos__transac_8bf3ac_idx'), models.Index(fields=['status'], name='pagamentos__status_eef4c0_idx'), models.Index(fields=['usuario', 'status'], name='pagamentos__usuario_bff826_idx'), models.Index(fields=['mensalidade'], name='pagamentos__mensali_69f0ff_idx')],
            },
        ),
    ]
