# Generated by Django 5.0.14 on 2025-12-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0078_cobrancapix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancapix',
            name='qr_code_url',
            field=models.URLField(blank=True, help_text='Link para visualizar/compartilhar o QR Code', max_length=500, verbose_name='URL do QR Code'),
        ),
        migrations.AlterField(
            model_name='cobrancapix',
            name='qr_code',
            field=models.TextField(blank=True, help_text='Código EMV para gerar imagem do QR Code', verbose_name='QR Code'),
        ),
    ]
