# Generated by Django 5.0.14 on 2025-12-18 01:52

import django.db.models.deletion
import nossopainel.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0079_cobrancapix_qr_code_url_alter_cobrancapix_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLimite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anual', models.DecimalField(decimal_places=2, default=Decimal('81000.00'), help_text='Valor máximo anual permitido para contas MEI', max_digits=12, verbose_name='Limite Anual MEI (R$)')),
                ('margem_seguranca', models.IntegerField(default=10, help_text='Percentual de margem (ex: 10 = alerta em 90%)', verbose_name='Margem de Segurança (%)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Limite',
                'verbose_name_plural': 'Configurações de Limite',
                'db_table': 'cadastros_configuracaolimite',
            },
        ),
        migrations.CreateModel(
            name='CredencialAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_identificacao', models.CharField(help_text='Ex: Minha Credencial FastDePix', max_length=100, verbose_name='Nome de Identificação')),
                ('tipo_integracao', models.CharField(choices=[('fastdepix', 'FastDePix'), ('mercado_pago', 'Mercado Pago'), ('efi_bank', 'Efi Bank')], max_length=20, verbose_name='Tipo de Integração')),
                ('api_key', models.CharField(blank=True, help_text='Token de autenticação (formato: fdpx_...)', max_length=255, verbose_name='API Key')),
                ('api_client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID')),
                ('api_client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret')),
                ('api_access_token', models.CharField(blank=True, max_length=500, verbose_name='Access Token')),
                ('api_certificado', models.FileField(blank=True, null=True, upload_to=nossopainel.models.certificado_upload_path, verbose_name='Certificado (.p12)')),
                ('ambiente_sandbox', models.BooleanField(default=False, verbose_name='Ambiente Sandbox')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credenciais_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial API',
                'verbose_name_plural': 'Credenciais API',
                'db_table': 'cadastros_credencialapi',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='credencial',
            field=models.ForeignKey(blank=True, help_text='Selecione uma credencial salva ou deixe vazio para usar credenciais específicas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_bancarias', to='nossopainel.credencialapi', verbose_name='Credencial API'),
        ),
    ]
