# Generated by Django 5.0.14 on 2025-12-18 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0080_add_credencial_api_and_configuracao_limite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alerta_limite', 'Alerta de Limite'), ('limite_atingido', 'Limite Atingido'), ('mudanca_plano', 'Mudança de Plano'), ('info', 'Informação'), ('aviso', 'Aviso')], default='info', max_length=30)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_sistema', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação do Sistema',
                'verbose_name_plural': 'Notificações do Sistema',
                'db_table': 'cadastros_notificacaosistema',
                'ordering': ['-criada_em'],
            },
        ),
    ]
