# Generated by Django 5.0.14 on 2025-12-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0081_add_notificacao_sistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientecontabancaria',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Indica se esta associação está ativa. Cliente só pode ter UMA associação ativa.', verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='clientecontabancaria',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
