# Generated by Django 5.0.14 on 2025-12-18 03:49

from django.conf import settings
from django.db import migrations, models


def convert_empty_to_null(apps, schema_editor):
    """Converte strings vazias para NULL nos campos de PIX e beneficiario."""
    ContaBancaria = apps.get_model('nossopainel', 'ContaBancaria')
    ContaBancaria.objects.filter(chave_pix='').update(chave_pix=None)
    ContaBancaria.objects.filter(tipo_chave_pix='').update(tipo_chave_pix=None)
    ContaBancaria.objects.filter(beneficiario='').update(beneficiario=None)


def convert_null_to_empty(apps, schema_editor):
    """Reverse: converte NULL para strings vazias."""
    ContaBancaria = apps.get_model('nossopainel', 'ContaBancaria')
    ContaBancaria.objects.filter(chave_pix__isnull=True).update(chave_pix='')
    ContaBancaria.objects.filter(tipo_chave_pix__isnull=True).update(tipo_chave_pix='')
    ContaBancaria.objects.filter(beneficiario__isnull=True).update(beneficiario='')


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0082_add_ativo_to_clientecontabancaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. Remover constraint unique_together antiga
        migrations.AlterUniqueTogether(
            name='contabancaria',
            unique_together=set(),
        ),
        # 2. Alterar campos para permitir NULL
        migrations.AlterField(
            model_name='contabancaria',
            name='beneficiario',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Beneficiário'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('celular', 'Celular'), ('aleatoria', 'Chave Aleatória')], max_length=50, null=True, verbose_name='Tipo de Chave PIX'),
        ),
        # 3. Converter strings vazias existentes para NULL
        migrations.RunPython(convert_empty_to_null, convert_null_to_empty),
        # 4. Adicionar nova constraint condicional
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(condition=models.Q(('chave_pix__isnull', False)), fields=('usuario', 'chave_pix'), name='unique_usuario_chave_pix'),
        ),
    ]
