# Generated by Django 5.0.14 on 2025-12-18 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0083_fix_contabancaria_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='forma_pgto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nossopainel.tipos_pgto', verbose_name='Forma de pagamento'),
        ),
    ]
