# Generated by Django 5.0.14 on 2025-12-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0084_cliente_forma_pgto_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_pgto',
            name='dados_bancarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formas_pagamento', to='nossopainel.dadosbancarios', verbose_name='Dados Bancários'),
        ),
    ]
