# Generated by Django 5.0.14 on 2025-12-19 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0085_tipos_pgto_dados_bancarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipos_pgto',
            name='nome_identificacao',
            field=models.CharField(blank=True, help_text='Nome para identificar esta forma de pagamento (ex: PIX NuBank)', max_length=255, null=True, verbose_name='Nome de Identificação'),
        ),
        migrations.AddField(
            model_name='tipos_pgto',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('pf', 'Pessoa Física'), ('mei', 'MEI')], default='pf', max_length=10, null=True, verbose_name='Tipo de Conta'),
        ),
    ]
