# Generated by Django 5.0.14 on 2025-12-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0086_tipos_pgto_nome_identificacao_tipo_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='links_planos_fastdepix',
            field=models.JSONField(blank=True, default=dict, help_text='Mapeamento de plano_id -> URL do link personalizado', verbose_name='Links FastDePix por Plano'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='tipo_cobranca_fastdepix',
            field=models.CharField(blank=True, choices=[('qrcode', 'QR Code + Copia e Cola'), ('link_personalizado', 'Link Personalizado')], default='link_personalizado', max_length=30, null=True, verbose_name='Tipo de Cobrança FastDePix'),
        ),
    ]
