# Generated by Django 5.0.14 on 2025-12-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0087_contabancaria_links_planos_fastdepix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='links_planos_fastdepix',
        ),
        migrations.CreateModel(
            name='PlanoLinkPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL do link FastDePix para este plano', verbose_name='Link de Pagamento')),
                ('valor_configurado', models.DecimalField(decimal_places=2, help_text='Valor do plano no momento em que o link foi configurado', max_digits=7, verbose_name='Valor quando configurado')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_planos', to='nossopainel.contabancaria', verbose_name='Conta Bancária FastDePix')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_pagamento', to='nossopainel.plano', verbose_name='Plano de Adesão')),
            ],
            options={
                'verbose_name': 'Link de Pagamento do Plano',
                'verbose_name_plural': 'Links de Pagamento dos Planos',
                'db_table': 'cadastros_planolinkpagamento',
                'ordering': ['plano__nome', 'plano__telas'],
                'unique_together': {('plano', 'conta_bancaria')},
            },
        ),
    ]
