# Generated by Django 5.0.14 on 2025-12-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0088_remove_contabancaria_links_planos_fastdepix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='tipo_cobranca_fastdepix',
            field=models.CharField(blank=True, choices=[('painel_cliente', 'Painel do Cliente'), ('link_fastdepix', 'Link FastDePix'), ('qrcode', 'QR Code + Copia e Cola')], default='painel_cliente', max_length=30, null=True, verbose_name='Tipo de Cobrança FastDePix'),
        ),
    ]
