# Generated by Django 5.0.14 on 2025-12-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0089_atualiza_tipos_cobranca_fastdepix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF do cliente (opcional, util para pagamentos)', max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dados_atualizados_painel',
            field=models.BooleanField(default=False, help_text='Indica se o cliente ja atualizou seus dados no painel de pagamentos', verbose_name='Dados atualizados no painel'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimo_acesso_painel',
            field=models.DateTimeField(blank=True, help_text='Data/hora do ultimo acesso do cliente ao painel de pagamentos', null=True, verbose_name='Ultimo acesso ao painel'),
        ),
    ]
