# Generated by Django 5.0.14 on 2025-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0090_cliente_cpf_cliente_dados_atualizados_painel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='webhook_id',
            field=models.CharField(blank=True, help_text='ID do webhook registrado na API (para atualizar/remover)', max_length=100, verbose_name='Webhook ID'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Chave secreta para validar webhooks HMAC-SHA256 (gerada ao registrar webhook)', max_length=255, verbose_name='Webhook Secret'),
        ),
    ]
