# Generated by Django 5.0.14 on 2025-12-22 20:50

from django.db import migrations, models


def criar_configuracoes_iniciais(apps, schema_editor):
    """Popula os jobs iniciais de agendamento."""
    ConfiguracaoAgendamento = apps.get_model('nossopainel', 'ConfiguracaoAgendamento')

    jobs = [
        {
            'nome': 'envios_vencimento',
            'nome_exibicao': 'Envios de Vencimento',
            'descricao': 'Notificações de vencimento e atraso de mensalidades. Envia mensagens automáticas para clientes com mensalidades a vencer ou vencidas.',
            'icone': 'mail',
            'horario': 'A cada 1 minuto',
            'ativo': True,
            'bloqueado': False,
            'ordem': 1,
            'templates_mensagem': {
                'observacao_fastdepix': 'OBSERVAÇÃO: Estamos mudando a forma como os clientes devem fazer seus pagamentos e não aceitaremos mais pagamento enviados na chave pix anterior. Você precisa acessar o link do nosso Painel do Cliente, acessar com seu número de telefone e realizar o pagamento da mensalidade que estará em aberto na tela inicial.'
            }
        },
        {
            'nome': 'tarefas_envio_db',
            'nome_exibicao': 'Tarefas de Envio (Banco)',
            'descricao': 'Executa tarefas de envio customizadas configuradas no banco de dados (TarefaEnvio). Permite envios personalizados para ativos, cancelados ou avulsos.',
            'icone': 'database',
            'horario': 'A cada 1 minuto',
            'ativo': True,
            'bloqueado': True,
            'ordem': 2,
            'templates_mensagem': {}
        },
        {
            'nome': 'gp_futebol',
            'nome_exibicao': 'GP Futebol',
            'descricao': 'Envia banners de futebol para grupos WhatsApp. Utiliza imagens do Telegram.',
            'icone': 'trophy',
            'horario': '08:00',
            'ativo': True,
            'bloqueado': False,
            'ordem': 3,
            'templates_mensagem': {}
        },
        {
            'nome': 'gp_vendas',
            'nome_exibicao': 'GP Vendas',
            'descricao': 'Envia propaganda para grupos OLX e vendas.',
            'icone': 'shopping-cart',
            'horario': '10:00',
            'ativo': True,
            'bloqueado': False,
            'ordem': 4,
            'templates_mensagem': {}
        },
        {
            'nome': 'mensalidades_canceladas',
            'nome_exibicao': 'Mensalidades Canceladas',
            'descricao': 'Ofertas progressivas para clientes cancelados. Envia mensagens de recuperação com descontos progressivos.',
            'icone': 'user-x',
            'horario': '17:00',
            'ativo': True,
            'bloqueado': True,
            'ordem': 5,
            'templates_mensagem': {}
        },
        {
            'nome': 'telegram_connection',
            'nome_exibicao': 'Telegram Connection',
            'descricao': 'Baixa banners e imagens do Telegram para uso em campanhas.',
            'icone': 'send',
            'horario': '23:00',
            'ativo': True,
            'bloqueado': True,
            'ordem': 6,
            'templates_mensagem': {}
        },
        {
            'nome': 'upload_telegram',
            'nome_exibicao': 'Upload Telegram',
            'descricao': 'Processa e organiza imagens baixadas do Telegram.',
            'icone': 'upload',
            'horario': '23:50',
            'ativo': True,
            'bloqueado': True,
            'ordem': 7,
            'templates_mensagem': {}
        },
        {
            'nome': 'backup_db',
            'nome_exibicao': 'Backup do Banco',
            'descricao': 'Realiza backup do banco SQLite para o Google Drive.',
            'icone': 'hard-drive',
            'horario': 'A cada 60 minutos',
            'ativo': True,
            'bloqueado': True,
            'ordem': 8,
            'templates_mensagem': {}
        },
    ]

    for job in jobs:
        ConfiguracaoAgendamento.objects.create(**job)


def reverter_configuracoes(apps, schema_editor):
    """Remove os jobs iniciais."""
    ConfiguracaoAgendamento = apps.get_model('nossopainel', 'ConfiguracaoAgendamento')
    ConfiguracaoAgendamento.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0091_add_webhook_fields_contabancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Identificador único do job (ex: envios_vencimento)', max_length=100, unique=True, verbose_name='Nome do Job')),
                ('nome_exibicao', models.CharField(help_text='Nome amigável para exibir na interface', max_length=100, verbose_name='Nome de Exibição')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do job', verbose_name='Descrição')),
                ('icone', models.CharField(default='calendar', help_text='Nome do ícone (Lucide Icons)', max_length=50, verbose_name='Ícone')),
                ('horario', models.CharField(blank=True, help_text='Horário de execução (ex: 08:00) ou frequência (ex: 1min, 60min)', max_length=50, verbose_name='Horário/Frequência')),
                ('ativo', models.BooleanField(default=True, help_text='Se o job está ativo e será executado', verbose_name='Ativo')),
                ('bloqueado', models.BooleanField(default=False, help_text='Se True, não pode ser editado pela interface web', verbose_name='Bloqueado')),
                ('templates_mensagem', models.JSONField(blank=True, default=dict, help_text='JSON com templates de mensagem personalizáveis', verbose_name='Templates de Mensagem')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na lista', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado Em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado Em')),
            ],
            options={
                'verbose_name': 'Configuração de Agendamento',
                'verbose_name_plural': 'Configurações de Agendamentos',
                'db_table': 'cadastros_configuracaoagendamento',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.RunPython(criar_configuracoes_iniciais, reverter_configuracoes),
    ]
