# Generated by Django 5.0.14 on 2025-12-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0095_desbloquear_todos_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancapix',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor líquido após taxas', max_digits=10, null=True, verbose_name='Valor Recebido (R$)'),
        ),
        migrations.AddField(
            model_name='cobrancapix',
            name='valor_taxa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa cobrada pela integração', max_digits=10, null=True, verbose_name='Taxa (R$)'),
        ),
    ]
