# Generated by Django 5.0.14 on 2025-12-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0097_add_templates_mensagem_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaosistema',
            name='tipo',
            field=models.CharField(choices=[('alerta_limite', 'Alerta de Limite'), ('limite_atingido', 'Limite Atingido'), ('mudanca_plano', 'Mudança de Plano'), ('pagamento_confirmado', 'Pagamento Confirmado'), ('info', 'Informação'), ('aviso', 'Aviso')], default='info', max_length=30),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='URL do endpoint de push do navegador')),
                ('p256dh', models.CharField(help_text='Chave pública p256dh do cliente', max_length=255)),
                ('auth', models.CharField(help_text='Chave de autenticação do cliente', max_length=255)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User-Agent do navegador (para identificação)', max_length=500)),
                ('ativo', models.BooleanField(default=True, help_text='Se False, a subscription expirou ou foi cancelada')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'db_table': 'cadastros_pushsubscription',
                'indexes': [models.Index(fields=['usuario', 'ativo'], name='cadastros_p_usuario_1ca9f6_idx')],
                'unique_together': {('usuario', 'endpoint')},
            },
        ),
    ]
