# Generated by Django 5.0.14 on 2025-12-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0101_encrypt_api_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='api_access_token',
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='api_client_secret',
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='webhook_secret',
        ),
        migrations.RemoveField(
            model_name='credencialapi',
            name='api_access_token',
        ),
        migrations.RemoveField(
            model_name='credencialapi',
            name='api_client_secret',
        ),
        migrations.RemoveField(
            model_name='credencialapi',
            name='api_key',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='_api_access_token',
            field=models.TextField(blank=True, db_column='api_access_token', default='', help_text='Obrigatório para Mercado Pago', verbose_name='Access Token (encriptado)'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='_api_client_secret',
            field=models.TextField(blank=True, db_column='api_client_secret', default='', help_text='Armazenado de forma segura com FERNET', verbose_name='Client Secret (encriptado)'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='_api_key',
            field=models.TextField(blank=True, db_column='api_key', default='', help_text='Token de autenticação (obrigatório para FastDePix - formato: fdpx_...)', verbose_name='API Key (encriptado)'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='_webhook_secret',
            field=models.TextField(blank=True, db_column='webhook_secret', default='', help_text='Chave secreta para validar webhooks HMAC-SHA256 (gerada ao registrar webhook)', verbose_name='Webhook Secret (encriptado)'),
        ),
        migrations.AddField(
            model_name='credencialapi',
            name='_api_access_token',
            field=models.TextField(blank=True, db_column='api_access_token', default='', verbose_name='Access Token (encriptado)'),
        ),
        migrations.AddField(
            model_name='credencialapi',
            name='_api_client_secret',
            field=models.TextField(blank=True, db_column='api_client_secret', default='', verbose_name='Client Secret (encriptado)'),
        ),
        migrations.AddField(
            model_name='credencialapi',
            name='_api_key',
            field=models.TextField(blank=True, db_column='api_key', default='', help_text='Token de autenticação (formato: fdpx_...)', verbose_name='API Key (encriptado)'),
        ),
    ]
