# Generated by Django 5.0.14 on 2025-12-26 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0102_remove_contabancaria_api_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tem_assinatura',
            field=models.BooleanField(default=True, verbose_name='Possui assinatura'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nossopainel.plano'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nossopainel.servidor'),
        ),
    ]
