# Generated by Django 5.0.14 on 2025-12-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0103_separar_cliente_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='País'),
        ),
    ]
