# Generated by Django 5.0.14 on 2026-01-05 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0104_add_pais_field_to_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='forma_pgto',
            field=models.ForeignKey(blank=True, help_text='Forma de pagamento registrada no momento do pagamento (histórico imutável)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nossopainel.tipos_pgto', verbose_name='Forma de Pagamento'),
        ),
    ]
