# Generated by Django 5.0.14 on 2026-01-05
# Data migration to populate forma_pgto for existing paid mensalidades

from django.db import migrations


def populate_forma_pgto(apps, schema_editor):
    """
    Popula o campo forma_pgto em mensalidades já pagas.
    Usa a forma de pagamento atual do cliente como fallback histórico.
    """
    Mensalidade = apps.get_model('nossopainel', 'Mensalidade')

    # Buscar mensalidades pagas sem forma_pgto definida
    mensalidades = Mensalidade.objects.filter(
        pgto=True,
        forma_pgto__isnull=True
    ).select_related('cliente')

    updated_count = 0
    for mensalidade in mensalidades:
        if mensalidade.cliente and mensalidade.cliente.forma_pgto_id:
            mensalidade.forma_pgto_id = mensalidade.cliente.forma_pgto_id
            mensalidade.save(update_fields=['forma_pgto'])
            updated_count += 1

    print(f"\n[Data Migration] Populado forma_pgto em {updated_count} mensalidades pagas.")


def reverse_populate(apps, schema_editor):
    """Reversão: remove forma_pgto das mensalidades."""
    Mensalidade = apps.get_model('nossopainel', 'Mensalidade')
    Mensalidade.objects.filter(pgto=True).update(forma_pgto=None)
    print("\n[Data Migration] Removido forma_pgto de mensalidades pagas.")


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0105_add_forma_pgto_to_mensalidade'),
    ]

    operations = [
        migrations.RunPython(populate_forma_pgto, reverse_populate),
    ]
