# Generated by Django 5.0.14 on 2026-01-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0106_populate_mensalidade_forma_pgto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='whatsapp_lid',
            field=models.CharField(blank=True, db_index=True, help_text='Linked ID do contato no WhatsApp (preenchido automaticamente via webhook)', max_length=50, null=True, verbose_name='WhatsApp LID'),
        ),
    ]
