# Generated by Django 5.0.14 on 2026-03-04 02:13

import django.core.validators
import django.db.models.deletion
import nossopainel.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0116_servidor_cor_etiqueta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to=nossopainel.models.atendimento_imagem_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Imagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem de Atendimento',
                'verbose_name_plural': 'Imagens de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='CategoriaAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Atendimento',
                'verbose_name_plural': 'Categorias de Atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhes', models.TextField(verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Atendimento',
                'verbose_name_plural': 'Registros de Atendimento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Atendimento',
                'verbose_name_plural': 'Tipos de Atendimento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='telefoneleads',
            options={'verbose_name': 'Telefone Lead', 'verbose_name_plural': 'Telefones Leads'},
        ),
        migrations.RenameIndex(
            model_name='mensagemenviadawpp',
            new_name='cadastros_m_usuario_524f10_idx',
            old_name='nossopainel_msg_envio_idx',
        ),
        migrations.AlterField(
            model_name='historicoexecucaotarefa',
            name='status',
            field=models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('erro', 'Erro'), ('concluido', 'Concluído')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(choices=[('CLUB', 'CLUB'), ('PLAY', 'PLAY'), ('PlayON', 'PlayON'), ('ALPHA', 'ALPHA'), ('SEVEN', 'SEVEN'), ('FIVE', 'FIVE'), ('GF', 'GF'), ('WAREZ', 'WAREZ'), ('GENIAL', 'GENIAL')], max_length=255),
        ),
        migrations.AddField(
            model_name='categoriaatendimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_atendimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroatendimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nossopainel.categoriaatendimento', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='registroatendimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='nossopainel.cliente'),
        ),
        migrations.AddField(
            model_name='registroatendimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atendimentoimagem',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='nossopainel.registroatendimento'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='nossopainel.categoriaatendimento'),
        ),
        migrations.AddField(
            model_name='tipoatendimento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_atendimento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroatendimento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nossopainel.tipoatendimento', verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaatendimento',
            unique_together={('nome', 'usuario')},
        ),
        migrations.AlterUniqueTogether(
            name='tipoatendimento',
            unique_together={('nome', 'categoria', 'usuario')},
        ),
    ]
