# Generated by Django 5.0.14 on 2026-03-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0117_add_registro_atendimento'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriaatendimento',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tipoatendimento',
            unique_together={('nome', 'categoria')},
        ),
        migrations.AlterField(
            model_name='categoriaatendimento',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.RemoveField(
            model_name='categoriaatendimento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tipoatendimento',
            name='usuario',
        ),
    ]
