# Generated by Django 5.0.14 on 2026-03-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0118_atendimento_global_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatendimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('resolvido', 'Resolvido')], default='pendente', max_length=10, verbose_name='Status'),
        ),
    ]
