# Generated by Django 5.0.14 on 2026-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0119_atendimento_add_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaatendimento',
            name='cor',
            field=models.CharField(default='#0dcaf0', help_text='Cor do badge em hexadecimal (ex: #0dcaf0)', max_length=7, verbose_name='Cor'),
        ),
    ]
