# Generated by Django 5.0.14 on 2026-03-06 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0120_categoria_atendimento_add_cor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAtendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendentes', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_atendente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Atendente',
                'verbose_name_plural': 'Perfis de Atendentes',
                'db_table': 'cadastros_perfilatendente',
            },
        ),
        migrations.CreateModel(
            name='PermissoesAtendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_clientes', models.BooleanField(default=True, verbose_name='Clientes')),
                ('nav_cadastros', models.BooleanField(default=False, verbose_name='Cadastros')),
                ('nav_whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('nav_relatorios', models.BooleanField(default=False, verbose_name='Relatórios')),
                ('nav_logs', models.BooleanField(default=False, verbose_name='Logs')),
                ('nav_configuracoes', models.BooleanField(default=False, verbose_name='Configurações')),
                ('perfil_estatisticas', models.BooleanField(default=False, verbose_name='Estatísticas (Visão Geral)')),
                ('perfil_exportar', models.BooleanField(default=False, verbose_name='Exportar Dados')),
                ('dash_card_clientes', models.BooleanField(default=True, verbose_name='Card: Clientes Ativos')),
                ('dash_card_recebido', models.BooleanField(default=False, verbose_name='Card: Valor Recebido no Mês')),
                ('dash_card_a_receber', models.BooleanField(default=False, verbose_name='Card: À Receber no Mês')),
                ('dash_card_planos', models.BooleanField(default=False, verbose_name='Card: Resumo de Planos')),
                ('dash_card_adesao', models.BooleanField(default=False, verbose_name='Card: Adesão e Cancelamentos')),
                ('dash_card_estados', models.BooleanField(default=False, verbose_name='Card: Clientes por Estado')),
                ('dash_card_servidor', models.BooleanField(default=False, verbose_name='Card: Clientes por Servidor')),
                ('dash_tab_evolucao', models.BooleanField(default=False, verbose_name='Aba: Evolução de Patrimônio')),
                ('dash_tab_adesao', models.BooleanField(default=False, verbose_name='Aba: Adesão e Cancelamentos')),
                ('dash_tab_receita', models.BooleanField(default=False, verbose_name='Aba: Receita Anual')),
                ('atendente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='nossopainel.perfilatendente')),
            ],
            options={
                'verbose_name': 'Permissões de Atendente',
                'verbose_name_plural': 'Permissões de Atendentes',
                'db_table': 'cadastros_permissoesatendente',
            },
        ),
    ]
