# Generated by Django 5.0.14 on 2026-03-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0121_add_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilatendente',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim do expediente'),
        ),
        migrations.AddField(
            model_name='perfilatendente',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início do expediente'),
        ),
        migrations.AddField(
            model_name='perfilatendente',
            name='intervalo_fim',
            field=models.TimeField(blank=True, null=True, verbose_name='Fim do intervalo'),
        ),
        migrations.AddField(
            model_name='perfilatendente',
            name='intervalo_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Início do intervalo'),
        ),
        migrations.AddField(
            model_name='perfilatendente',
            name='tem_intervalo',
            field=models.BooleanField(default=False, verbose_name='Possui intervalo/almoço'),
        ),
    ]
