# Generated by Django 5.0.14 on 2025-05-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0034_conteudom3u8_remove_cliente_telas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='data_vencimento',
            new_name='data_vencimento2',
        ),
    ]
