# Generated by Django 5.0.14 on 2025-04-29 07:37

import cadastros.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0035_qtd_tela_usuario_secrettokenapi_dt_criacao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-data_adesao']},
        ),
        migrations.AddField(
            model_name='contadoaplicativo',
            name='device_id_is_a_mac',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\(?\\d{2}\\)? ?\\d{4,5}-?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='horarioenvios',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_vencimento',
            field=models.DateField(default=cadastros.models.default_vencimento, verbose_name='Data do vencimento'),
        ),
        migrations.AddConstraint(
            model_name='contadoaplicativo',
            constraint=models.UniqueConstraint(fields=('cliente', 'app', 'device_id'), name='unique_device_per_cliente_app'),
        ),
    ]
