# Generated by Django 5.0.14 on 2025-04-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0036_alter_cliente_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contadoaplicativo',
            name='device_id_is_a_mac',
        ),
        migrations.AddField(
            model_name='aplicativo',
            name='device_has_mac',
            field=models.BooleanField(default=False),
        ),
    ]
