# Generated by Django 5.0.14 on 2025-05-03 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0037_remove_contadoaplicativo_device_id_is_a_mac_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qtd_tela',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telas',
        ),
        migrations.AlterModelOptions(
            name='contadoaplicativo',
            options={'verbose_name': 'Conta do Aplicativo', 'verbose_name_plural': 'Contas dos Aplicativos'},
        ),
        migrations.AlterModelOptions(
            name='conteudom3u8',
            options={'verbose_name': 'Conteúdo M3U8', 'verbose_name_plural': 'Conteúdos M3U8'},
        ),
        migrations.AlterModelOptions(
            name='mensagemenviadawpp',
            options={'verbose_name': 'Mensagem Enviada ao WhatsApp', 'verbose_name_plural': 'Mensagens Enviadas ao WhatsApp'},
        ),
        migrations.AlterModelOptions(
            name='tipos_pgto',
            options={'verbose_name': 'Tipo de Pagamento', 'verbose_name_plural': 'Tipos de Pagamentos'},
        ),
        migrations.AddField(
            model_name='plano',
            name='telas',
            field=models.IntegerField(default=1, verbose_name='Número de telas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_pagamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='horarioenvios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_cancelamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do cancelamento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_notif_wpp1',
            field=models.DateField(blank=True, null=True, verbose_name='Data envio notificação PROMO'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='dt_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data do pagamento'),
        ),
        migrations.AddIndex(
            model_name='contadoaplicativo',
            index=models.Index(fields=['cliente', 'app'], name='cadastros_c_cliente_d49878_idx'),
        ),
        migrations.AddIndex(
            model_name='contadoaplicativo',
            index=models.Index(fields=['device_id'], name='cadastros_c_device__90d23d_idx'),
        ),
        migrations.DeleteModel(
            name='Qtd_tela',
        ),
    ]
