# Generated by Django 5.0.14 on 2025-05-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0038_remove_qtd_tela_usuario_remove_cliente_telas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_pagamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento inicial'),
        ),
    ]
