# Generated by Django 5.0.14 on 2025-05-05 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0039_remove_cliente_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoindicacao',
            name='valor_minimo_mensalidade',
            field=models.DecimalField(decimal_places=2, default=13.99, max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
