# Generated by Django 5.0.14 on 2025-05-07 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0040_planoindicacao_valor_minimo_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbancarios',
            name='wpp',
            field=models.TextField(default=8393329190, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor para desconto ou bonificação'),
        ),
        migrations.AlterField(
            model_name='planoindicacao',
            name='valor_minimo_mensalidade',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor mínimo a ser mantido na mensalidade'),
        ),
    ]
