# Generated by Django 5.0.14 on 2025-05-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0041_dadosbancarios_wpp_alter_planoindicacao_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosbancarios',
            name='wpp',
            field=models.CharField(max_length=20),
        ),
    ]
