# Generated by Django 5.0.14 on 2025-05-07 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0042_alter_dadosbancarios_wpp'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contadoaplicativo',
            name='unique_device_per_cliente_app',
        ),
    ]
