# Generated by Django 5.0.14 on 2025-12-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JampabetUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Senha (hash)')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('hits', models.IntegerField(default=0, verbose_name='Acertos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário JampaBet',
                'verbose_name_plural': 'Usuários JampaBet',
                'db_table': 'jampabet_user',
                'ordering': ['-points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID Externo (API-Football)')),
                ('home_team', models.CharField(max_length=100, verbose_name='Time da Casa')),
                ('away_team', models.CharField(max_length=100, verbose_name='Time Visitante')),
                ('home_team_logo', models.URLField(blank=True, verbose_name='Logo Time Casa')),
                ('away_team_logo', models.URLField(blank=True, verbose_name='Logo Time Visitante')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
                ('competition', models.CharField(max_length=100, verbose_name='Competição')),
                ('competition_logo', models.URLField(blank=True, verbose_name='Logo Competição')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Estádio')),
                ('location', models.CharField(choices=[('home', 'Casa'), ('away', 'Fora')], max_length=10, verbose_name='Local (Bahia)')),
                ('round', models.CharField(blank=True, max_length=50, verbose_name='Rodada')),
                ('status', models.CharField(choices=[('upcoming', 'Agendado'), ('live', 'Ao Vivo'), ('finished', 'Encerrado'), ('cancelled', 'Cancelado'), ('postponed', 'Adiado')], default='upcoming', max_length=20, verbose_name='Status')),
                ('result_bahia', models.IntegerField(blank=True, null=True, verbose_name='Gols Bahia')),
                ('result_opponent', models.IntegerField(blank=True, null=True, verbose_name='Gols Adversário')),
                ('elapsed_time', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Jogo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'jampabet_match',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Registro'), ('login', 'Login'), ('logout', 'Logout'), ('create_bet', 'Criar Aposta'), ('update_bet', 'Atualizar Aposta'), ('delete_bet', 'Excluir Aposta'), ('register_result', 'Registrar Resultado')], max_length=50, verbose_name='Ação')),
                ('entity_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Entidade')),
                ('entity_id', models.IntegerField(blank=True, null=True, verbose_name='ID da Entidade')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Novo Valor')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jampabet.jampabetuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'jampabet_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_win_bahia', models.IntegerField(verbose_name='Vitória Bahia - Gols Bahia')),
                ('home_win_opponent', models.IntegerField(verbose_name='Vitória Bahia - Gols Adversário')),
                ('draw_bahia', models.IntegerField(verbose_name='Empate - Gols Bahia')),
                ('draw_opponent', models.IntegerField(verbose_name='Empate - Gols Adversário')),
                ('points_earned', models.IntegerField(default=0, verbose_name='Pontos Ganhos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='jampabet.jampabetuser', verbose_name='Usuário')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='jampabet.match', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'db_table': 'jampabet_bet',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'match')},
            },
        ),
    ]
