# Generated by Django 5.0.14 on 2025-12-08 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jampabetuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='E-mail verificado'),
        ),
        migrations.AddField(
            model_name='jampabetuser',
            name='verification_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiração do token'),
        ),
        migrations.AddField(
            model_name='jampabetuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de verificação'),
        ),
        migrations.AlterField(
            model_name='jampabetuser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, verbose_name='Senha (hash)'),
        ),
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=6, verbose_name='Token (6 dígitos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tokens', to='jampabet.jampabetuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Token de Login',
                'verbose_name_plural': 'Tokens de Login',
                'db_table': 'jampabet_login_token',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'token', 'used'], name='jampabet_lo_user_id_020e76_idx'), models.Index(fields=['expires_at'], name='jampabet_lo_expires_9b4223_idx')],
            },
        ),
    ]
