# Generated by Django 5.0.14 on 2025-12-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0002_add_2fa_and_verification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrazilianTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID do time na API-Football', unique=True, verbose_name='ID API-Football')),
                ('name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('short_name', models.CharField(help_text='Nome abreviado para exibicao (ex: Sport, Bahia, Vitoria)', max_length=30, verbose_name='Nome curto')),
                ('display_name', models.CharField(blank=True, help_text='Nome personalizado para exibicao (ex: Vicetoria para o Vitoria)', max_length=50, verbose_name='Nome de exibicao')),
                ('logo_url', models.URLField(blank=True, help_text='URL do logo fornecido pela API', verbose_name='Logo URL (API)')),
                ('custom_logo_url', models.URLField(blank=True, help_text='URL de logo personalizado (sobrescreve o da API)', verbose_name='Logo URL (personalizado)')),
                ('code', models.CharField(blank=True, help_text='Codigo de 3 letras (ex: BAH, VIT, SPT)', max_length=5, verbose_name='Codigo')),
                ('country', models.CharField(default='Brazil', max_length=50, verbose_name='Pais')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('stadium', models.CharField(blank=True, max_length=150, verbose_name='Estadio')),
                ('stadium_capacity', models.IntegerField(blank=True, null=True, verbose_name='Capacidade')),
                ('founded', models.IntegerField(blank=True, null=True, verbose_name='Ano de fundacao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Time Brasileiro',
                'verbose_name_plural': 'Times Brasileiros',
                'db_table': 'jampabet_brazilian_team',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['external_id'], name='jampabet_br_externa_659738_idx'), models.Index(fields=['name'], name='jampabet_br_name_a8173c_idx'), models.Index(fields=['short_name'], name='jampabet_br_short_n_8eba8f_idx')],
            },
        ),
    ]
