# Generated by Django 5.0.14 on 2025-12-09 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0003_brazilian_team_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID da competicao na API-Football', unique=True, verbose_name='ID API-Football')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='Nome curto')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
                ('competition_type', models.CharField(choices=[('league', 'Liga/Campeonato'), ('cup', 'Copa'), ('state', 'Estadual')], default='league', max_length=20, verbose_name='Tipo')),
                ('country', models.CharField(default='Brazil', max_length=50, verbose_name='Pais')),
                ('current_season', models.IntegerField(blank=True, null=True, verbose_name='Temporada atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_tracked', models.BooleanField(default=False, help_text='Se True, as partidas desta competicao serao sincronizadas', verbose_name='Monitorada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Competicao',
                'verbose_name_plural': 'Competicoes',
                'db_table': 'jampabet_competition',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['external_id'], name='jampabet_co_externa_73a60e_idx'), models.Index(fields=['is_tracked'], name='jampabet_co_is_trac_d0f45f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID da partida na API-Football', unique=True, verbose_name='ID API-Football')),
                ('season', models.IntegerField(verbose_name='Temporada')),
                ('round', models.CharField(blank=True, max_length=50, verbose_name='Rodada')),
                ('round_number', models.IntegerField(blank=True, null=True, verbose_name='Numero da rodada')),
                ('home_team_api_id', models.IntegerField(blank=True, null=True)),
                ('away_team_api_id', models.IntegerField(blank=True, null=True)),
                ('home_team_name', models.CharField(blank=True, max_length=100)),
                ('away_team_name', models.CharField(blank=True, max_length=100)),
                ('home_team_logo', models.URLField(blank=True)),
                ('away_team_logo', models.URLField(blank=True)),
                ('home_goals', models.IntegerField(blank=True, null=True, verbose_name='Gols casa')),
                ('away_goals', models.IntegerField(blank=True, null=True, verbose_name='Gols visitante')),
                ('home_goals_ht', models.IntegerField(blank=True, null=True, verbose_name='Gols casa (1T)')),
                ('away_goals_ht', models.IntegerField(blank=True, null=True, verbose_name='Gols visitante (1T)')),
                ('date', models.DateTimeField(verbose_name='Data/Hora')),
                ('venue', models.CharField(blank=True, max_length=150, verbose_name='Estadio')),
                ('venue_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('live', 'Ao Vivo'), ('finished', 'Encerrado'), ('postponed', 'Adiado'), ('cancelled', 'Cancelado'), ('suspended', 'Suspenso'), ('interrupted', 'Interrompido'), ('abandoned', 'Abandonado')], default='scheduled', max_length=20, verbose_name='Status')),
                ('elapsed_time', models.IntegerField(blank=True, null=True, verbose_name='Tempo decorrido')),
                ('last_api_update', models.DateTimeField(blank=True, null=True, verbose_name='Ultima atualizacao da API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_fixtures', to='jampabet.brazilianteam', verbose_name='Time visitante')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='jampabet.competition', verbose_name='Competicao')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_fixtures', to='jampabet.brazilianteam', verbose_name='Time da casa')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'jampabet_fixture',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['external_id'], name='jampabet_fi_externa_8f5164_idx'), models.Index(fields=['competition', 'season'], name='jampabet_fi_competi_cd8198_idx'), models.Index(fields=['date'], name='jampabet_fi_date_8a3ec3_idx'), models.Index(fields=['status'], name='jampabet_fi_status_3ac15c_idx'), models.Index(fields=['home_team'], name='jampabet_fi_home_te_ce8f04_idx'), models.Index(fields=['away_team'], name='jampabet_fi_away_te_e029ed_idx'), models.Index(fields=['round_number'], name='jampabet_fi_round_n_ebb79e_idx')],
            },
        ),
    ]
