# Generated by Django 5.0.14 on 2025-12-09 18:58

from django.db import migrations, models


def sync_role_from_is_admin(apps, schema_editor):
    """Sincroniza o campo role com base no is_admin existente"""
    JampabetUser = apps.get_model('jampabet', 'JampabetUser')
    # Atualiza usuarios admin
    JampabetUser.objects.filter(is_admin=True).update(role='admin')


def reverse_sync(apps, schema_editor):
    """Reverso: nao faz nada, pois is_admin permanece"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0004_competition_and_fixture_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='jampabetuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('user', 'Palpiteiro')], default='user', max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='jampabetuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador (legado)'),
        ),
        migrations.RunPython(sync_role_from_is_admin, reverse_sync),
    ]
