# Generated by Django 5.0.14 on 2025-12-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0005_add_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Chave de acesso da API-Football', max_length=100, verbose_name='Chave da API')),
                ('api_enabled', models.BooleanField(default=True, help_text='Se desabilitado, nao fara consultas a API externa', verbose_name='API Habilitada')),
                ('polling_interval', models.IntegerField(default=60, help_text='Intervalo em segundos para consultar partidas ao vivo (minimo 30s)', verbose_name='Intervalo de Polling (segundos)')),
                ('auto_start_matches', models.BooleanField(default=True, help_text='Mudar status para "live" quando chegar o horario de inicio', verbose_name='Iniciar Partidas Automaticamente')),
                ('auto_update_scores', models.BooleanField(default=True, help_text='Buscar placares em tempo real via API', verbose_name='Atualizar Placares Automaticamente')),
                ('minutes_before_match', models.IntegerField(default=10, help_text='Bloquear palpites X minutos antes do inicio', verbose_name='Minutos antes para bloquear palpites')),
                ('last_poll_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo polling')),
                ('last_poll_status', models.CharField(blank=True, max_length=50, verbose_name='Status do ultimo polling')),
                ('last_poll_message', models.TextField(blank=True, verbose_name='Mensagem do ultimo polling')),
                ('total_api_calls_today', models.IntegerField(default=0, verbose_name='Chamadas API hoje')),
                ('last_api_call_reset', models.DateField(blank=True, null=True, verbose_name='Data do ultimo reset de chamadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuracao da API',
                'verbose_name_plural': 'Configuracoes da API',
                'db_table': 'jampabet_api_config',
            },
        ),
    ]
