# Generated by Django 5.0.14 on 2025-12-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0006_add_api_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='points_exact_draw',
            field=models.IntegerField(default=1, help_text='Pontuacao para quem acertar o placar exato em caso de empate', verbose_name='Pontos por placar exato de empate'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='points_exact_victory',
            field=models.IntegerField(default=3, help_text='Pontuacao para quem acertar o placar exato em caso de vitoria do Bahia', verbose_name='Pontos por placar exato de triunfo'),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='round_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor que o usuario deve pagar por rodada com palpite feito', max_digits=10, verbose_name='Valor por rodada'),
        ),
    ]
