# Generated by Django 5.0.14 on 2026-01-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0007_add_scoring_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='live_period',
            field=models.CharField(blank=True, help_text='Status da API: 1H, HT, 2H, ET, P, FT, etc.', max_length=10, null=True, verbose_name='Período'),
        ),
    ]
