# Generated by Django 5.0.14 on 2026-01-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jampabet', '0008_add_live_period_to_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfig',
            name='require_2fa',
            field=models.BooleanField(default=False, help_text='Se ativado, envia codigo de verificacao por e-mail ao fazer login', verbose_name='Exigir verificacao por e-mail (2FA)'),
        ),
    ]
