# Generated by Django 5.0.14 on 2025-12-20 04:26

import django.db.models.deletion
import painel_cliente.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nossopainel', '0090_cliente_cpf_cliente_dados_atualizados_painel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubdominioPainelCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdominio', models.CharField(help_text='Nome do subdominio (ex: meunegocio para meunegocio.pagar.cc)', max_length=63, unique=True)),
                ('dominio_completo', models.CharField(help_text='Dominio completo (ex: meunegocio.pagar.cc)', max_length=255, unique=True)),
                ('nome_exibicao', models.CharField(help_text='Nome exibido no painel (ex: Meu Negocio IPTV)', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logo do painel (recomendado: 200x200px)', null=True, upload_to=painel_cliente.models.painel_logo_upload_path)),
                ('cor_primaria', models.CharField(default='#0d6efd', help_text='Cor primaria em hexadecimal (ex: #0d6efd)', max_length=7)),
                ('cor_secundaria', models.CharField(default='#6c757d', help_text='Cor secundaria em hexadecimal (ex: #6c757d)', max_length=7)),
                ('whatsapp_suporte', models.CharField(blank=True, help_text='Numero do WhatsApp para suporte (ex: 5571999999999)', max_length=20)),
                ('mensagem_suporte', models.TextField(default='Ola! Preciso de ajuda com minha assinatura.', help_text='Mensagem padrao para o WhatsApp')),
                ('texto_boas_vindas', models.CharField(default='Bem-vindo ao seu painel!', help_text='Mensagem de boas-vindas exibida no dashboard', max_length=255)),
                ('ativo', models.BooleanField(default=True, help_text='Se desativado, o painel nao estara acessivel')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('admin_responsavel', models.ForeignKey(help_text='Usuario do NossoPainel que administra este subdominio', on_delete=django.db.models.deletion.CASCADE, related_name='subdominios_painel', to=settings.AUTH_USER_MODEL)),
                ('conta_bancaria', models.ForeignKey(blank=True, help_text='Conta FastDePix para processar pagamentos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdominios_painel', to='nossopainel.contabancaria')),
                ('criado_por', models.ForeignKey(blank=True, help_text='Admin Superior que criou este subdominio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subdominios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subdominio do Painel',
                'verbose_name_plural': 'Subdominios do Painel',
                'db_table': 'painel_cliente_subdominio',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SessaoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='Token seguro da sessao', max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP do cliente no momento do login')),
                ('user_agent', models.TextField(help_text='User-Agent do navegador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acesso', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField(help_text='Data/hora de expiracao da sessao')),
                ('ativo', models.BooleanField(default=True, help_text='Sessao ativa ou encerrada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_painel', to='nossopainel.cliente')),
                ('subdominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='painel_cliente.subdominiopainelcliente')),
            ],
            options={
                'verbose_name': 'Sessao do Cliente',
                'verbose_name_plural': 'Sessoes dos Clientes',
                'db_table': 'painel_cliente_sessao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('identificador', models.CharField(help_text='Telefone ou email tentado', max_length=255)),
                ('sucesso', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('subdominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas_login', to='painel_cliente.subdominiopainelcliente')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
                'db_table': 'painel_cliente_tentativa_login',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='subdominiopainelcliente',
            index=models.Index(fields=['subdominio'], name='painel_clie_subdomi_5e2a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='subdominiopainelcliente',
            index=models.Index(fields=['ativo'], name='painel_clie_ativo_2e1cca_idx'),
        ),
        migrations.AddIndex(
            model_name='subdominiopainelcliente',
            index=models.Index(fields=['admin_responsavel'], name='painel_clie_admin_r_0c44a7_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocliente',
            index=models.Index(fields=['token'], name='painel_clie_token_a695f5_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocliente',
            index=models.Index(fields=['cliente', 'ativo'], name='painel_clie_cliente_890f71_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaocliente',
            index=models.Index(fields=['expira_em'], name='painel_clie_expira__4d875d_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativalogin',
            index=models.Index(fields=['ip_address', 'criado_em'], name='painel_clie_ip_addr_2e6380_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativalogin',
            index=models.Index(fields=['subdominio', 'criado_em'], name='painel_clie_subdomi_e43626_idx'),
        ),
    ]
