# Generated by Django 5.0.14 on 2025-12-20 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nossopainel', '0090_cliente_cpf_cliente_dados_atualizados_painel_and_more'),
        ('painel_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Codigo de 6 digitos', max_length=6)),
                ('email_enviado', models.EmailField(help_text='Email para onde o codigo foi enviado', max_length=254)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(help_text='Data/hora de expiracao do codigo')),
                ('usado', models.BooleanField(default=False, help_text='Se o codigo ja foi usado com sucesso')),
                ('tentativas', models.PositiveIntegerField(default=0, help_text='Numero de tentativas de uso (max 3)')),
            ],
            options={
                'verbose_name': 'Codigo OTP',
                'verbose_name_plural': 'Codigos OTP',
                'db_table': 'painel_cliente_codigo_otp',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.RemoveIndex(
            model_name='sessaocliente',
            name='painel_clie_expira__4d875d_idx',
        ),
        migrations.AddField(
            model_name='sessaocliente',
            name='metodo_auth',
            field=models.CharField(default='otp_email', help_text='Metodo de autenticacao usado (otp_email, otp_sms, etc)', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessaocliente',
            name='expira_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora de expiracao (null = sessao permanente)', null=True),
        ),
        migrations.AlterField(
            model_name='sessaocliente',
            name='ultimo_acesso',
            field=models.DateTimeField(auto_now=True, help_text='Atualizado a cada acesso para controle de inatividade'),
        ),
        migrations.AddIndex(
            model_name='sessaocliente',
            index=models.Index(fields=['ultimo_acesso'], name='painel_clie_ultimo__e3dc33_idx'),
        ),
        migrations.AddField(
            model_name='codigootp',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp', to='nossopainel.cliente'),
        ),
        migrations.AddField(
            model_name='codigootp',
            name='subdominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp', to='painel_cliente.subdominiopainelcliente'),
        ),
        migrations.AddIndex(
            model_name='codigootp',
            index=models.Index(fields=['cliente', 'subdominio', 'criado_em'], name='painel_clie_cliente_39fd10_idx'),
        ),
        migrations.AddIndex(
            model_name='codigootp',
            index=models.Index(fields=['codigo', 'usado', 'expira_em'], name='painel_clie_codigo_87e35f_idx'),
        ),
    ]
