# Generated by Django 5.0.14 on 2025-12-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_cliente', '0002_add_codigo_otp_and_sessao_permanente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaocliente',
            name='metodo_auth',
            field=models.CharField(default='telefone', help_text='Metodo de autenticacao usado (telefone, etc)', max_length=20),
        ),
        migrations.AlterField(
            model_name='subdominiopainelcliente',
            name='cor_primaria',
            field=models.CharField(default='#8B5CF6', help_text='Cor primaria em hexadecimal (ex: #8B5CF6)', max_length=7),
        ),
        migrations.AlterField(
            model_name='subdominiopainelcliente',
            name='cor_secundaria',
            field=models.CharField(default='#06B6D4', help_text='Cor secundaria em hexadecimal (ex: #06B6D4)', max_length=7),
        ),
        migrations.DeleteModel(
            name='CodigoOTP',
        ),
    ]
