# Generated by Django 5.0.14 on 2025-12-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel_cliente', '0003_remove_codigo_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativalogin',
            name='identificador',
            field=models.CharField(help_text='Telefone tentado', max_length=255),
        ),
    ]
